import random
from core.translation_data import NATURES
from core.translation_data import POKEMON_NAMES
from core.moves import get_move

POKEMON_TALENTS = {
    "Sinistea-Phony": {"normal": ["Armurouillée"], "hidden": "Corps Maudit"},
    "Sinistea-Authentic": {"normal": ["Armurouillée"], "hidden": "Corps Maudit"},
    "Polteageist-Phony": {"normal": ["Armurouillée"], "hidden": "Corps Maudit"},
    "Polteageist-Authentic": {"normal": ["Armurouillée"], "hidden": "Corps Maudit"},
    "Vivillon-Elegant":     {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Monsoon":     {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Ocean":       {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-River":       {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Savanna":     {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Sun":         {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Typhoon":     {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Meadow":      {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Polar":       {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Tundra":      {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Garden":      {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Sandstorm":   {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Icy-Snow":    {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Modern":      {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Marine":      {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Archipelago": {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-High-Plains": {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Jungle":      {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Fancy":       {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Vivillon-Pokeball":    {"normal": ["Écran Poudre", "Œil Composé"], "hidden": "Garde Amie"},
    "Cherrim-Overcast": {"normal": ["Don Floral"], "hidden": None},
    "Cherrim-Sunshine": {"normal": ["Don Floral"], "hidden": None},
    "Dudunsparce-Two-Segment": {"normal": ["Sérénité", "Fuite"], "hidden": "Phobique"},
    "Dudunsparce-Three-Segment": {"normal": ["Sérénité", "Fuite"], "hidden": "Phobique"},
    "Gimmighoul-Chest":   {"normal": ["Phobique"], "hidden": None},
    "Gimmighoul-Roaming": {"normal": ["Fuite"], "hidden": None},
    "Ogerpon-Teal-Mask":        {"normal": ["Acharné"], "hidden": None},
    "Ogerpon-Cornerstone-Mask": {"normal": ["Brise Moule"], "hidden": None},
    "Ogerpon-Wellspring-Mask":  {"normal": ["Absorb Eau"], "hidden": None},
    "Ogerpon-Hearthflame-Mask": {"normal": ["Régé-Force"], "hidden": None},
    "Palafin-Zero": {"normal": ["Héros Modeste"], "hidden": None},
    "Palafin-Hero": {"normal": ["Héros Modeste"], "hidden": None},
    "Urshifu-Single-Strike": {"normal": ["Poing Invisible"], "hidden": None},
    "Urshifu-Rapid-Strike":  {"normal": ["Poing Invisible"], "hidden": None},
    "Eiscue-Ice-Face":   {"normal": ["Tête de Glace"], "hidden": None},
    "Eiscue-Noice-Face": {"normal": ["Tête de Glace"], "hidden": None},
    "Meowstic-Male": {
    "normal": ["Regard Vif", "Infiltration"],
    "hidden": "Farceu"
},
"Meowstic-Female": {
    "normal": ["Regard Vif", "Infiltration"],
    "hidden": "Battant"
},
    "Squawkabilly-Green": {
    "normal": ["Intimidation", "Agitation"],
    "hidden": "Cran"
},
"Squawkabilly-Blue": {
    "normal": ["Intimidation", "Agitation"],
    "hidden": "Sans Limite"
},
"Squawkabilly-Yellow": {
    "normal": ["Intimidation", "Agitation"],
    "hidden": "Sans Limite"
},
"Squawkabilly-White": {
    "normal": ["Intimidation", "Agitation"],
    "hidden": "Sans Limite"
},
    "Maushold-Family3": {
    "normal": ["Garde Amie", "Bajoues"],
    "hidden": "Technicien"
},
"Maushold-Family4": {
    "normal": ["Garde Amie", "Bajoues"],
    "hidden": "Technicien"
},
    "Bastiodon":    {"normal": ["Fermeté"], "hidden": "Anti-Bruit"},
    "Bibarel":      {"normal": ["Simple", "Inconscient"], "hidden": "Lunatique"},
    "Bidoof":       {"normal": ["Simple", "Inconscient"], "hidden": "Lunatique"},
    "Budew":        {"normal": ["Médic Nature", "Point Poison"], "hidden": "Feuille Garde"},
    "Buizel":       {"normal": ["Glissade"], "hidden": "Absorb Eau"},
    "Burmy-Plant": {"normal": ["Mue"], "hidden": None},
    "Burmy-Sandy": {"normal": ["Mue"], "hidden": None},
    "Burmy-Trash": {"normal": ["Mue"], "hidden": None},
    "Wormadam-Plant": {"normal": ["Anticipation"], "hidden": "Envelocape"},
    "Wormadam-Sandy": {"normal": ["Anticipation"], "hidden": "Envelocape"},
    "Wormadam-Trash": {"normal": ["Anticipation"], "hidden": "Envelocape"},
    "Cherubi":      {"normal": ["Chlorophylle"], "hidden": None},
    "Combee":       {"normal": ["Cherche Miel"], "hidden": "Agitation"},
    "Cranidos":     {"normal": ["Brise Moule"], "hidden": "Sans Limite"},
    "Empoleon":     {"normal": ["Torrent"], "hidden": "Acharné"},
    "Floatzel":     {"normal": ["Glissade"], "hidden": "Absorb Eau"},
    "Gastrodon":    {"normal": ["Glue", "Lavabo"], "hidden": "Force Sable"},
    "Grotle":       {"normal": ["Engrais"], "hidden": "Coque Armure"},
    "Infernape":    {"normal": ["Brasier"], "hidden": "Poing de Fer"},
    "Kricketot":    {"normal": ["Fuite"], "hidden": "Fouille"},
    "Kricketune":   {"normal": ["Essaim"], "hidden": "Technicien"},
    "Absol":        {"normal": ["Pression"], "hidden": "Chanceux"},
    "Aggron":       {"normal": ["Fermeté", "Tête de Roc"], "hidden": "Heavy Metal"},
    "Anorith":      {"normal": ["Armurbaston"], "hidden": "Glissade"},
    "Armaldo":      {"normal": ["Armurbaston"], "hidden": "Glissade"},
    "Aron":         {"normal": ["Fermeté", "Tête de Roc"], "hidden": "Heavy Metal"},
    "Azurill":      {"normal": ["Isograisse", "Coloforce"], "hidden": "Herbivore"},
    "Baltoy":       {"normal": ["Lévitation"], "hidden": None},
    "Banette":      {"normal": ["Insomnia", "Fouille"], "hidden": "Corps Maudit"},
    "Beautifly":    {"normal": ["Essaim"], "hidden": "Rivalité"},
    "Blaziken":     {"normal": ["Brasier"], "hidden": "Turbo"},
    "Breloom":      {"normal": ["Pose Spore", "Soin Poison"], "hidden": "Technicien"},
    "Cacnea":       {"normal": ["Voile Sable"], "hidden": "Absorb Eau"},
    "Cacturne":     {"normal": ["Voile Sable"], "hidden": "Absorb Eau"},
    "Camerupt":     {"normal": ["Armumagma", "Solide Roc"], "hidden": "Colérique"},
    "Carvanha":     {"normal": ["Peau Dure"], "hidden": "Turbo"},
    "Cascoon":      {"normal": ["Mue"], "hidden": None},
    "Castform":     {"normal": ["Météo"], "hidden": None},
    "Chimecho":     {"normal": ["Lévitation"], "hidden": None},
    "Claydol":      {"normal": ["Lévitation"], "hidden": None},
    "Combusken":    {"normal": ["Brasier"], "hidden": "Turbo"},
    "Cradily":      {"normal": ["Ventouse"], "hidden": "Lavabo"},
    "Delcatty":     {"normal": ["Joli Sourire", "Normalise"], "hidden": "Peau Miracle"},
    "Dusclops":     {"normal": ["Pression"], "hidden": "Fouille"},
    "Duskull":      {"normal": ["Lévitation"], "hidden": "Fouille"},
    "Dustox":       {"normal": ["Écran Poudre"], "hidden": "Œil Composé"},
    "Electrike":    {"normal": ["Statik", "Paratonnerre"], "hidden": "Minus"},
    "Exploud":      {"normal": ["Anti-Bruit"], "hidden": "Querelleur"},
    "Feebas":       {"normal": ["Glissade", "Benêt"], "hidden": "Adaptabilité"},
    "Gardevoir":    {"normal": ["Synchro"], "hidden": "Télépathe"},
    "Grovyle":      {"normal": ["Engrais"], "hidden": "Délestage"},
    "Gulpin":       {"normal": ["Glue", "Suintement"], "hidden": "Gloutonnerie"},
    "Hariyama":     {"normal": ["Isograisse", "Cran"], "hidden": "Sans Limite"},
    "Illumise":     {"normal": ["Benêt", "Lentiteintée"], "hidden": "Farceur"},
    "Kecleon":      {"normal": ["Déguisement"], "hidden": "Protéen"},
    "Kirlia":       {"normal": ["Synchro", "Calque"], "hidden": "Télépathe"},
    "Bagon":        {"normal": ["Tête de Roc"], "hidden": "Sans Limite"},
    "Shelgon":      {"normal": ["Tête de Roc"], "hidden": "Envelocape"},
    "Salamence":    {"normal": ["Intimidation"], "hidden": "Impudence"},
    "Beldum":       {"normal": ["Corps Sain"], "hidden": "Light Metal"},
    "Metang":       {"normal": ["Corps Sain"], "hidden": "Light Metal"},
    "Metagross":    {"normal": ["Corps Sain"], "hidden": "Light Metal"},
    "Regirock":     {"normal": ["Corps Sain"], "hidden": "Fermeté"},
    "Regice":       {"normal": ["Corps Sain"], "hidden": "Corps Gel"},
    "Registeel":    {"normal": ["Corps Sain"], "hidden": "Light Metal"},
    "Latias":       {"normal": ["Lévitation"], "hidden": None},
    "Latios":       {"normal": ["Lévitation"], "hidden": None},
    "Kyogre":       {"normal": ["Crachin"], "hidden": None},
    "Groudon":      {"normal": ["Sécheresse"], "hidden": None},
    "Rayquaza":     {"normal": ["Air Lock"], "hidden": None},
    "Jirachi":      {"normal": ["Sérénité"], "hidden": None},
    "Deoxys":       {"normal": ["Pression"], "hidden": None},
    "Snorunt":      {"normal": ["Attention", "Corps Gel"], "hidden": "Lunatique"},
    "Glalie":       {"normal": ["Attention", "Corps Gel"], "hidden": "Lunatique"},
    "Spheal":       {"normal": ["Isograisse", "Corps Gel"], "hidden": "Benêt"},
    "Sealeo":       {"normal": ["Isograisse", "Corps Gel"], "hidden": "Benêt"},
    "Walrein":      {"normal": ["Isograisse", "Corps Gel"], "hidden": "Benêt"},
    "Wynaut":       {"normal": ["Marque Ombre"], "hidden": "Télépathe"},
    "Koraidon":     {"normal": ["Pouls Orichalque"], "hidden": None},
    "Miraidon":     {"normal": ["Moteur Hadron"], "hidden": None},
    "Terapagos":    {"normal": ["Téra-Carapace"], "hidden": None},
    "Rotom-Heat":   {"normal": ["Lévitation"], "hidden": None},
    "Rotom-Wash":   {"normal": ["Lévitation"], "hidden": None},
    "Rotom-Frost":  {"normal": ["Lévitation"], "hidden": None},
    "Rotom-Fan":    {"normal": ["Lévitation"], "hidden": None},
    "Rotom-Mow":    {"normal": ["Lévitation"], "hidden": None},
    "Treecko":      {"normal": ["Engrais"], "hidden": "Délestage"},
    "Grovyle":      {"normal": ["Engrais"], "hidden": "Délestage"},
    "Sceptile":     {"normal": ["Engrais"], "hidden": "Délestage"},
    "Torchic":      {"normal": ["Brasier"], "hidden": "Turbo"},
    "Combusken":    {"normal": ["Brasier"], "hidden": "Turbo"},
    "Blaziken":     {"normal": ["Brasier"], "hidden": "Turbo"},
    "Mudkip":       {"normal": ["Torrent"], "hidden": "Moiteur"},
    "Marshtomp":    {"normal": ["Torrent"], "hidden": "Moiteur"},
    "Swampert":     {"normal": ["Torrent"], "hidden": "Moiteur"},
    "Taillow":      {"normal": ["Cran"], "hidden": "Querelleur"},
    "Swellow":      {"normal": ["Cran"], "hidden": "Querelleur"},
    "Banette":      {"normal": ["Insomnia", "Fouille"], "hidden": "Corps Maudit"},
    "Swablu":       {"normal": ["Médic Nature"], "hidden": "Ciel Gris"},
    "Altaria":      {"normal": ["Médic Nature"], "hidden": "Ciel Gris"},
    "Spinda":       {"normal": ["Tempo Perso", "Pieds Confus"], "hidden": "Contestation"},
    "Spoink":       {"normal": ["Tempo Perso", "Isograisse"], "hidden": "Gloutonnerie"},
    "Grumpig":      {"normal": ["Tempo Perso", "Isograisse"], "hidden": "Gloutonnerie"},
    "Zangoose":     {"normal": ["Vaccin"], "hidden": "Rage Poison"},
    "Seviper":      {"normal": ["Mue"], "hidden": "Infiltration"},
    "Solrock":      {"normal": ["Lévitation"], "hidden": None},
    "Lunatone":     {"normal": ["Lévitation"], "hidden": None},
    "Barboach":     {"normal": ["Benêt", "Anticipation"], "hidden": "Hydratation"},
    "Whiscash":     {"normal": ["Benêt", "Anticipation"], "hidden": "Hydratation"},
    "Corphish":     {"normal": ["Hyper Cutter", "Coque Armure"], "hidden": "Adaptabilité"},
    "Crawdaunt":    {"normal": ["Hyper Cutter", "Coque Armure"], "hidden": "Adaptabilité"},
    "Bulbasaur":    {"normal": ["Engrais"], "hidden": "Chlorophylle"},
    "Ivysaur":      {"normal": ["Engrais"], "hidden": "Chlorophylle"},
    "Venusaur":     {"normal": ["Engrais"], "hidden": "Chlorophylle"},
    "Charmander":   {"normal": ["Brasier"], "hidden": "Force Soleil"},
    "Charmeleon":   {"normal": ["Brasier"], "hidden": "Force Soleil"},
    "Charizard":    {"normal": ["Brasier"], "hidden": "Force Soleil"},
    "Squirtle":     {"normal": ["Torrent"], "hidden": "Cuvette"},
    "Wartortle":    {"normal": ["Torrent"], "hidden": "Cuvette"},
    "Blastoise":    {"normal": ["Torrent"], "hidden": "Cuvette"},
    "Caterpie":     {"normal": ["Écran Poudre"], "hidden": "Fuite"},
    "Metapod":      {"normal": ["Mue"], "hidden": "Fuite"},
    "Butterfree":   {"normal": ["Œil Composé"], "hidden": "Lentiteintée"},
    "Weedle":       {"normal": ["Écran Poudre"], "hidden": "Fuite"},
    "Kakuna":       {"normal": ["Mue"], "hidden": "Fuite"},
    "Beedrill":     {"normal": ["Essaim"], "hidden": "Sniper"},
    "Pidgey":       {"normal": ["Regard Vif", "Téméraire"], "hidden": "Cœur de Coq"},
    "Pidgeotto":    {"normal": ["Regard Vif", "Téméraire"], "hidden": "Cœur de Coq"},
    "Pidgeot":      {"normal": ["Regard Vif", "Téméraire"], "hidden": "Cœur de Coq"},
    "Rattata":      {"normal": ["Fuite", "Agitation"], "hidden": "Cran"},
    "Raticate":     {"normal": ["Fuite", "Agitation"], "hidden": "Cran"},
    "Spearow":     {"normal": ["Regard Vif"], "hidden": "Sniper"},
    "Fearow":      {"normal": ["Regard Vif"], "hidden": "Sniper"},
    "Ekans":       {"normal": ["Intimidation", "Mue"], "hidden": "Tension"},
    "Arbok":       {"normal": ["Intimidation", "Mue"], "hidden": "Tension"},
    "Pikachu":     {"normal": ["Statik"], "hidden": "Paratonnerre"},
    "Raichu":      {"normal": ["Statik"], "hidden": "Paratonnerre"},
    "Sandshrew":   {"normal": ["Voile Sable"], "hidden": "Baigne Sable"},
    "Sandslash":   {"normal": ["Voile Sable"], "hidden": "Baigne Sable"},
    "Nidoran♀":    {"normal": ["Point Poison", "Rivalité"], "hidden": "Agitation"},
    "Nidorina":    {"normal": ["Point Poison", "Rivalité"], "hidden": "Agitation"},
    "Nidoqueen":   {"normal": ["Point Poison", "Rivalité"], "hidden": "Sans Limite"},
    "Nidoran♂":    {"normal": ["Point Poison", "Rivalité"], "hidden": "Agitation"},
    "Nidorino":    {"normal": ["Point Poison", "Rivalité"], "hidden": "Agitation"},
    "Nidoking":    {"normal": ["Point Poison", "Rivalité"], "hidden": "Sans Limite"},
    "Clefairy":    {"normal": ["Joli Sourire", "Garde Magik"], "hidden": "Inconscient"},
    "Clefable":    {"normal": ["Joli Sourire", "Garde Magik"], "hidden": "Inconscient"},
    "Vulpix":      {"normal": ["Torche"], "hidden": "Sécheresse"},
    "Ninetales":   {"normal": ["Torche"], "hidden": "Sécheresse"},
    "Jigglypuff":   {"normal": ["Joli Sourire", "Gluco-Voile"], "hidden": "Garde Amie"},
    "Wigglytuff":   {"normal": ["Joli Sourire", "Gluco-Voile"], "hidden": "Garde Amie"},
    "Zubat":        {"normal": ["Attention"], "hidden": "Infiltration"},
    "Golbat":       {"normal": ["Attention"], "hidden": "Infiltration"},
    "Crobat":        {"normal": ["Attention"], "hidden": "Infiltration"},  
    "Oddish":        {"normal": ["Chlorophylle"], "hidden": "Fuite"},
    "Gloom":         {"normal": ["Chlorophylle"], "hidden": "Puanteur"},
    "Vileplume":     {"normal": ["Chlorophylle"], "hidden": "Effluves"},
    "Paras":         {"normal": ["Pose Spore", "Peau Sèche"], "hidden": "Moiteur"},
    "Parasect":      {"normal": ["Pose Spore", "Peau Sèche"], "hidden": "Moiteur"},
    "Venonat":       {"normal": ["Oeil Composé", "Pare-Balles"], "hidden": "Lentiteintée"},
    "Venomoth":      {"normal": ["Écran Poudre", "Pare-Balles"], "hidden": "Lentiteintée"},
    "Diglett":       {"normal": ["Voile Sable", "Pied Véloce"], "hidden": "Force Sable"},
    "Dugtrio":       {"normal": ["Voile Sable", "Pied Véloce"], "hidden": "Force Sable"},
    "Meowth":        {"normal": ["Ramassage", "Technicien"], "hidden": "Tension"},
    "Persian":       {"normal": ["Échauffement", "Technicien"], "hidden": "Tension"},
    "Psyduck":       {"normal": ["Moiteur", "Ciel Gris"], "hidden": "Battant"},
    "Golduck":       {"normal": ["Moiteur", "Ciel Gris"], "hidden": "Battant"},
    "Mankey":        {"normal": ["Esprit Vital", "Colérique"], "hidden": "Tension"},
    "Primeape":      {"normal": ["Esprit Vital", "Colérique"], "hidden": "Tension"},
    "Growlithe":     {"normal": ["Intimidation", "Torche"], "hidden": "Cœur Noble"},
    "Arcanine":      {"normal": ["Intimidation", "Torche"], "hidden": "Cœur Noble"},
    "Poliwag":       {"normal": ["Absorb Eau", "Moiteur"], "hidden": "Glissade"},
    "Poliwhirl":     {"normal": ["Absorb Eau", "Moiteur"], "hidden": "Glissade"},
    "Poliwrath":     {"normal": ["Absorb Eau", "Moiteur"], "hidden": "Coque Armure"},
    "Abra":          {"normal": ["Synchro", "Attention"], "hidden": "Garde Magik"},
    "Kadabra":       {"normal": ["Synchro", "Attention"], "hidden": "Garde Magik"},
    "Alakazam":      {"normal": ["Synchro", "Attention"], "hidden": "Garde Magik"},
    "Machop":        {"normal": ["Cran", "Annule Garde"], "hidden": "Poing de Fer"},
    "Machoke":       {"normal": ["Cran", "Annule Garde"], "hidden": "Poing de Fer"},
    "Machamp":       {"normal": ["Cran", "Annule Garde"], "hidden": "Poing de Fer"},
    "Tentacool":     {"normal": ["Corps Sain"], "hidden": "Cuvette"},
    "Tentacruel":    {"normal": ["Corps Sain"], "hidden": "Cuvette"},
    "Geodude":       {"normal": ["Tête de Roc", "Fermeté"], "hidden": "Voile Sable"},
    "Graveler":      {"normal": ["Tête de Roc", "Fermeté"], "hidden": "Voile Sable"},
    "Golem":         {"normal": ["Tête de Roc", "Fermeté"], "hidden": "Voile Sable"},
    "Ponyta":        {"normal": ["Fuite", "Torche"], "hidden": "Flamme Corps"},
    "Rapidash":      {"normal": ["Fuite", "Torche"], "hidden": "Flamme Corps"},
    "Slowpoke":      {"normal": ["Benêt", "Tempo Perso"], "hidden": "Régé-Force"},
    "Slowbro":       {"normal": ["Benêt", "Tempo Perso"], "hidden": "Régé-Force"},
    "Magnemite":     {"normal": ["Magnépiège", "Fermeté"], "hidden": "Analyste"},
    "Magneton":      {"normal": ["Magnépiège", "Fermeté"], "hidden": "Analyste"},
    "Farfetch'd":    {"normal": ["Attention"], "hidden": "Acharné"},
    "Doduo":         {"normal": ["Fuite", "Matinal"], "hidden": "Tension"},
    "Dodrio":        {"normal": ["Fuite", "Matinal"], "hidden": "Tension"},
    "Seel":          {"normal": ["Isograisse", "Hydratation"], "hidden": "Cœur de Coq"},
    "Dewgong":       {"normal": ["Isograisse", "Hydratation"], "hidden": "Cœur de Coq"},
    "Grimer":        {"normal": ["Puanteur", "Glue"], "hidden": "Poisseux"},
    "Muk":           {"normal": ["Puanteur", "Glue"], "hidden": "Poisseux"},
    "Shellder":      {"normal": ["Coque Armure", "Multi-Coups"], "hidden": "Envelocape"},
    "Cloyster":      {"normal": ["Coque Armure", "Multi-Coups"], "hidden": "Envelocape"},
    "Gastly":        {"normal": ["Lévitation"], "hidden": None},
    "Haunter":       {"normal": ["Lévitation"], "hidden": None},
    "Gengar":        {"normal": ["Lévitation"], "hidden": "Corps Maudit"},
    "Onix":          {"normal": ["Tête de Roc", "Fermeté"], "hidden": "Fermeté"},
    "Drowzee":       {"normal": ["Insomnia", "Prédiction"], "hidden": "Attention"},
    "Hypno":         {"normal": ["Insomnia", "Prédiction"], "hidden": "Attention"},
    "Krabby":        {"normal": ["Hyper Cutter", "Coque Armure"], "hidden": "Adaptabilité"},
    "Kingler":       {"normal": ["Hyper Cutter", "Coque Armure"], "hidden": "Adaptabilité"},
    "Voltorb":       {"normal": ["Anti-Bruit", "Statik"], "hidden": "Boom Final"},
    "Electrode":     {"normal": ["Anti-Bruit", "Statik"], "hidden": "Boom Final"},
    "Exeggcute":     {"normal": ["Chlorophylle"], "hidden": "Récolte"},
    "Exeggutor":     {"normal": ["Chlorophylle"], "hidden": "Récolte"},
    "Cubone":        {"normal": ["Tête de Roc", "Paratonnerre"], "hidden": "Armurbaston"},
    "Marowak":       {"normal": ["Tête de Roc", "Paratonnerre"], "hidden": "Armurbaston"},
    "Hitmonlee":     {"normal": ["Attention", "Impudence"], "hidden": "Délestage"},
    "Hitmonchan":    {"normal": ["Attention", "Poing de Fer"], "hidden": "Cran"},
    "Lickitung":     {"normal": ["Tempo Perso", "Benêt"], "hidden": "Nuage Final"},
    "Koffing":       {"normal": ["Lévitation"], "hidden": "Puanteur"},
    "Weezing":       {"normal": ["Lévitation"], "hidden": "Puanteur"},
    "Rhyhorn":       {"normal": ["Paratonnerre", "Téméraire"], "hidden": "Tête de Roc"},
    "Rhydon":        {"normal": ["Paratonnerre", "Téméraire"], "hidden": "Tête de Roc"},
    "Chansey":       {"normal": ["Médic Nature"], "hidden": "Cœur Soin"},
    "Tangela":       {"normal": ["Chlorophylle"], "hidden": "Feuille Garde"},
    "Kangaskhan":    {"normal": ["Querelleur", "Tension"], "hidden": "Attention"},
    "Horsea":        {"normal": ["Glissade"], "hidden": "Sniper"},
    "Seadra":        {"normal": ["Poison Point"], "hidden": "Sniper"},
    "Goldeen":       {"normal": ["Glissade", "Ignifu-Voile"], "hidden": "Cœur de Poisson"},
    "Seaking":       {"normal": ["Glissade", "Ignifu-Voile"], "hidden": "Cœur de Poisson"},
    "Staryu":        {"normal": ["Lumiattirance"], "hidden": "Analyste"},
    "Starmie":       {"normal": ["Lumiattirance"], "hidden": "Analyste"},
    "Mr. Mime":      {"normal": ["Anti-Bruit", "Filtre"], "hidden": "Technicien"},
    "Scyther":       {"normal": ["Essaim", "Technicien"], "hidden": "Impassible"},
    "Jynx":          {"normal": ["Benêt", "Prédiction"], "hidden": "Peau Sèche"},
    "Electabuzz":    {"normal": ["Statik"], "hidden": "Esprit Vital"},
    "Magmar":        {"normal": ["Corps Ardent"], "hidden": "Esprit Vital"},
    "Pinsir":        {"normal": ["Hyper Cutter", "Brise Moule"], "hidden": "Acharné"},
    "Enamorus-Incarnate": {"normal": ["Contestation"], "hidden": "Joli Sourire"},
    "Enamorus-Therian": {"normal": ["Envelocape"], "hidden": "Joli Sourire"},
    "Tauros":        {"normal": ["Intimidation", "Colérique"], "hidden": "Isograisse"},
    "Tauros-Paldean-Combat": {"normal": ["Intimidation", "Anger Point"], "hidden": "Rumination"},
    "Tauros-Paldean-Blaze": {"normal": ["Intimidation", "Anger Point"], "hidden": "Rumination"},
    "Tauros-Paldean-Aqua": {"normal": ["Intimidation", "Anger Point"], "hidden": "Rumination"},
    "Magikarp":      {"normal": ["Glissade"], "hidden": "Tension"},
    "Gyarados":      {"normal": ["Intimidation"], "hidden": "Brise Moule"},
    "Lapras":        {"normal": ["Absorb Eau", "Coque Armure"], "hidden": "Hydratation"},
    "Ditto":         {"normal": ["Imposteur"], "hidden": None},
    "Eevee":         {"normal": ["Fuite", "Adaptabilité"], "hidden": "Anticipation"},
    "Vaporeon":      {"normal": ["Absorb Eau"], "hidden": "Hydratation"},
    "Jolteon":       {"normal": ["Absorb Volt"], "hidden": "Agitation"},
    "Flareon":       {"normal": ["Absorb Feu"], "hidden": "Cran"},
    "Porygon":       {"normal": ["Traçage", "Télécharge"], "hidden": "Analyste"},
    "Omanyte":       {"normal": ["Glissade", "Coque Armure"], "hidden": "Brise Moule"},
    "Omastar":       {"normal": ["Glissade", "Coque Armure"], "hidden": "Brise Moule"},
    "Kabuto":        {"normal": ["Glissade", "Armurbaston"], "hidden": "Acharné"},
    "Kabutops":      {"normal": ["Glissade", "Armurbaston"], "hidden": "Acharné"},
    "Aerodactyl":    {"normal": ["Tête de Roc", "Pression"], "hidden": "Début Calme"},
    "Snorlax":       {"normal": ["Isograisse", "Impassible"], "hidden": "Gloutonnerie"},
    "Articuno":      {"normal": ["Pression"], "hidden": "Corps Gel"},
    "Zapdos":        {"normal": ["Pression"], "hidden": "Tension"},
    "Moltres":       {"normal": ["Pression"], "hidden": "Corps Ardent"},
    "Dratini":       {"normal": ["Mue"], "hidden": "Marvel Écaille"},
    "Dragonair":     {"normal": ["Mue"], "hidden": "Marvel Écaille"},
    "Dragonite":     {"normal": ["Attention"], "hidden": "Marvel Écaille"},
    "Mewtwo":        {"normal": ["Pression"], "hidden": "Tension"},
    "Mew":           {"normal": ["Synchro"], "hidden": None},
    "Bellsprout":    {"normal": ["Chlorophylle"], "hidden": "Gloutonnerie"},
    "Weepinbell":    {"normal": ["Chlorophylle"], "hidden": "Gloutonnerie"},
    "Victreebel":    {"normal": ["Chlorophylle"], "hidden": "Gloutonnerie"},
    "Bellossom":     {"normal": ["Chlorophylle"], "hidden": "Soin"},
    "Marill":        {"normal": ["Isograisse", "Coloforce"], "hidden": "Herbivore"},
    "Azumarill":     {"normal": ["Isograisse", "Coloforce"], "hidden": "Herbivore"},
    "Sudowoodo":     {"normal": ["Fermeté", "Tête de Roc"], "hidden": "Phobique"},
    "Politoed":      {"normal": ["Absorb Eau", "Moiteur"], "hidden": "Crachin"},
    "Hoppip":        {"normal": ["Chlorophylle", "Feuille Garde"], "hidden": "Délestage"},
    "Skiploom":      {"normal": ["Chlorophylle", "Feuille Garde"], "hidden": "Délestage"},
    "Jumpluff":      {"normal": ["Chlorophylle", "Feuille Garde"], "hidden": "Délestage"},
    "Aipom":         {"normal": ["Ramassage"], "hidden": "Technicien"},
    "Sunkern":       {"normal": ["Chlorophylle", "Engrais"], "hidden": "Matinal"},
    "Sunflora":      {"normal": ["Chlorophylle", "Force Soleil"], "hidden": "Matinal"},
    "Yanma":         {"normal": ["Regard Vif", "Vitesse"], "hidden": "Lentiteintée"},
    "Wooper":        {"normal": ["Absorb Eau", "Moiteur"], "hidden": "Inconscient"},
    "Quagsire":      {"normal": ["Absorb Eau", "Moiteur"], "hidden": "Inconscient"},
    "Espeon":        {"normal": ["Synchro"], "hidden": "Miroir Magik"},
    "Umbreon":       {"normal": ["Synchro"], "hidden": "Attention"},
    "Murkrow":       {"normal": ["Insomnia", "Chanceux"], "hidden": "Farceur"},
    "Slowking":      {"normal": ["Benêt", "Tempo Perso"], "hidden": "Régé-Force"},
    "Misdreavus":    {"normal": ["Lévitation"], "hidden": "Farceur"},
    "Unown":         {"normal": ["Lévitation"], "hidden": None},
    "Wobbuffet":     {"normal": ["Ventouse"], "hidden": "Télépathe"},
    "Girafarig":     {"normal": ["Attention", "Matinal"], "hidden": "Herbivore"},
    "Pineco":        {"normal": ["Fermeté"], "hidden": "Engrais"},
    "Forretress":    {"normal": ["Fermeté"], "hidden": "Engrais"},
    "Dunsparce":     {"normal": ["Sérénité", "Fuite"], "hidden": "Agitation"},
    "Gligar":        {"normal": ["Hyper Cutter", "Voile Sable"], "hidden": "Impassible"},
    "Steelix":       {"normal": ["Tête de Roc", "Fermeté"], "hidden": "Sans Limite"},
    "Snubbull":      {"normal": ["Intimidation", "Fuite"], "hidden": "Cran"},
    "Granbull":      {"normal": ["Intimidation", "Fuite"], "hidden": "Cran"},
    "Qwilfish":      {"normal": ["Point Poison", "Boom Final"], "hidden": "Intimidation"},
    "Scizor":        {"normal": ["Essaim", "Technicien"], "hidden": "Light Metal"},
    "Shuckle":       {"normal": ["Fermeté", "Gloutonnerie"], "hidden": "Contrôle"},
    "Heracross":     {"normal": ["Essaim", "Cran"], "hidden": "Acharné"},
    "Sneasel":       {"normal": ["Attention", "Pickpocket"], "hidden": "Acharné"},
    "Teddiursa":     {"normal": ["Ramassage", "Pied Véloce"], "hidden": "Querelleur"},
    "Ursaring":      {"normal": ["Cran", "Pied Véloce"], "hidden": "Querelleur"},
    "Slugma":        {"normal": ["Armumagma", "Corps Ardent"], "hidden": "Armurouillée"},
    "Magcargo":      {"normal": ["Armumagma", "Corps Ardent"], "hidden": "Armurouillée"},
    "Swinub":        {"normal": ["Isograisse", "Rideau Neige"], "hidden": "Benêt"},
    "Piloswine":     {"normal": ["Isograisse", "Rideau Neige"], "hidden": "Benêt"},
    "Corsola":       {"normal": ["Fermeté", "Tête de Roc"], "hidden": "Régé-Force"},
    "Remoraid":      {"normal": ["Sniper", "Lunatique"], "hidden": "Poing de Fer"},
    "Octillery":     {"normal": ["Sniper", "Ventouse"], "hidden": "Poing de Fer"},
    "Delibird":      {"normal": ["Isograisse", "Agitation"], "hidden": "Insomnia"},
    "Mantine":       {"normal": ["Absorb Eau", "Glissade"], "hidden": "Cuvette"},
    "Skarmory":      {"normal": ["Fermeté", "Regard Vif"], "hidden": "Armurouillée"},
    "Houndour":      {"normal": ["Torche", "Matinal"], "hidden": "Tension"},
    "Houndoom":      {"normal": ["Torche", "Matinal"], "hidden": "Tension"},
    "Kingdra":       {"normal": ["Sniper"], "hidden": "Glissade"},
    "Phanpy":        {"normal": ["Ramassage"], "hidden": "Voile Sable"},
    "Donphan":       {"normal": ["Armurbaston"], "hidden": "Voile Sable"},
    "Porygon2":      {"normal": ["Trace", "Télécharge"], "hidden": "Analyste"},
    "Stantler":      {"normal": ["Intimidation", "Insomnia"], "hidden": "Mirage"},
    "Smeargle":      {"normal": ["Technicien"], "hidden": "Moiteur"},
    "Tyrogue":       {"normal": ["Cran", "Attention"], "hidden": "Esprit Vital"},
    "Hitmontop":     {"normal": ["Technicien", "Tête de Roc"], "hidden": "Acharné"},
    "Smoochum":      {"normal": ["Benêt", "Prédiction"], "hidden": "Hydratation"},
    "Elekid":        {"normal": ["Statik"], "hidden": "Esprit Vital"},
    "Magby":         {"normal": ["Corps Ardent"], "hidden": "Esprit Vital"},
    "Miltank":       {"normal": ["Isograisse", "Querelleur"], "hidden": "Herbivore"},
    "Blissey":       {"normal": ["Médic Nature", "Sérénité"], "hidden": "Cœur Soin"},
    "Raikou":        {"normal": ["Pression"], "hidden": "Tension"},
    "Entei":         {"normal": ["Pression"], "hidden": "Tension"},
    "Suicune":       {"normal": ["Pression"], "hidden": "Tension"},
    "Larvitar":      {"normal": ["Voile Sable"], "hidden": "Téméraire"},
    "Pupitar":       {"normal": ["Mue"], "hidden": "Téméraire"},
    "Tyranitar":     {"normal": ["Sable Volant"], "hidden": "Tension"},
    "Lugia":         {"normal": ["Pression"], "hidden": "Multitype"},
    "Ho-Oh":         {"normal": ["Pression"], "hidden": "Régé-Force"},
    "Celebi":        {"normal": ["Médic Nature"], "hidden": None},
    "Turtwig":       {"normal": ["Engrais"], "hidden": "Coque Armure"},
    "Grotle":        {"normal": ["Engrais"], "hidden": "Coque Armure"},
    "Torterra":      {"normal": ["Engrais"], "hidden": "Coque Armure"},
    "Chimchar":      {"normal": ["Brasier"], "hidden": "Poing de Fer"},
    "Monferno":      {"normal": ["Brasier"], "hidden": "Poing de Fer"},
    "Infernape":     {"normal": ["Brasier"], "hidden": "Poing de Fer"},
    "Piplup":        {"normal": ["Torrent"], "hidden": "Acharné"},
    "Prinplup":      {"normal": ["Torrent"], "hidden": "Acharné"},
    "Empoleon":      {"normal": ["Torrent"], "hidden": "Acharné"},
    "Starly":        {"normal": ["Regard Vif"], "hidden": "Téméraire"},
    "Staravia":      {"normal": ["Intimidation"], "hidden": "Téméraire"},
    "Staraptor":     {"normal": ["Intimidation"], "hidden": "Téméraire"},
    "Bidoof":        {"normal": ["Inconscient", "Simple"], "hidden": "Insomnia"},
    "Bibarel":       {"normal": ["Inconscient", "Simple"], "hidden": "Isograisse"},
    "Kricketot":     {"normal": ["Fuite"], "hidden": "Technicien"},
    "Kricketune":    {"normal": ["Échauffement"], "hidden": "Technicien"},
    "Shinx":         {"normal": ["Rivalité", "Intimidation"], "hidden": "Cran"},
    "Luxio":         {"normal": ["Rivalité", "Intimidation"], "hidden": "Cran"},
    "Luxray":        {"normal": ["Rivalité", "Intimidation"], "hidden": "Cran"},
    "Budew":         {"normal": ["Médic Nature", "Point Poison"], "hidden": "Feuille Garde"},
    "Roserade":      {"normal": ["Point Poison", "Technicien"], "hidden": "Feuille Garde"},
    "Cranidos":      {"normal": ["Brise Moule"], "hidden": "Tête de Roc"},
    "Rampardos":     {"normal": ["Brise Moule"], "hidden": "Tête de Roc"},
    "Shieldon":      {"normal": ["Fermeté"], "hidden": "Anticipation"},
    "Bastiodon":     {"normal": ["Fermeté"], "hidden": "Anticipation"},
    "Mothim":        {"normal": ["Essaim"], "hidden": "Délestage"},
    "Combee":        {"normal": ["Essaim"], "hidden": "Cueillette"},
    "Vespiquen":     {"normal": ["Pression"], "hidden": "Tension"},
    "Pachirisu":     {"normal": ["Ramassage", "Fuite"], "hidden": "Voile Soin"},
    "Buizel":        {"normal": ["Glissade"], "hidden": "Agitation"},
    "Floatzel":      {"normal": ["Glissade"], "hidden": "Agitation"},
    "Cherubi":       {"normal": ["Chlorophylle"], "hidden": "Matinal"},
    "Shellos-East": {
        "normal": ["Sticky Hold", "Collecteur"],
        "hidden": "Sand Force"
    },
    "Shellos-West": {
        "normal": ["Sticky Hold", "Collecteur"],
        "hidden": "Sand Force"
    },
    "Gastrodon-East": {
        "normal": ["Sticky Hold", "Collecteur"],
        "hidden": "Sand Force"
    },
    "Gastrodon-West": {
        "normal": ["Sticky Hold", "Collecteur"],
        "hidden": "Sand Force"
    },
    "Ambipom":       {"normal": ["Technicien", "Ramassage"], "hidden": "Agitation"},
    "Drifloon":      {"normal": ["Déflagration", "Fuite"], "hidden": "Délestage"},
    "Drifblim":      {"normal": ["Déflagration", "Fuite"], "hidden": "Délestage"},
    "Buneary":       {"normal": ["Fuite", "Regard Vif"], "hidden": "Querelleur"},
    "Lopunny":       {"normal": ["Joli Sourire", "Querelleur"], "hidden": "Insomnia"},
    "Mismagius":     {"normal": ["Lévitation"], "hidden": None},
    "Honchkrow":     {"normal": ["Insomnia", "Chanceux"], "hidden": "Impudence"},
    "Glameow":       {"normal": ["Regard Vif", "Tempo Perso"], "hidden": "Déconcentration"},
    "Purugly":       {"normal": ["Regard Vif", "Tempo Perso"], "hidden": "Déconcentration"},
    "Chingling":     {"normal": ["Lévitation"], "hidden": None},
    "Stunky":        {"normal": ["Puanteur", "Boom Final"], "hidden": "Regard Vif"},
    "Skuntank":      {"normal": ["Puanteur", "Boom Final"], "hidden": "Regard Vif"},
    "Bronzor":       {"normal": ["Lévitation", "Anti-Bruit"], "hidden": "Lentiteintée"},
    "Bronzong":      {"normal": ["Lévitation", "Anti-Bruit"], "hidden": "Lentiteintée"},
    "Bonsly":        {"normal": ["Fermeté", "Tête de Roc"], "hidden": "Phobique"},
    "Mime Jr.":      {"normal": ["Anti-Bruit", "Filtre"], "hidden": "Technicien"},
    "Happiny":       {"normal": ["Sérénité", "Médic Nature"], "hidden": "Ami Cher"},
    "Chatot":        {"normal": ["Regard Vif", "Anti-Bruit"], "hidden": "Moiteur"},
    "Spiritomb":     {"normal": ["Pression"], "hidden": "Infiltration"},
    "Gible":         {"normal": ["Voile Sable"], "hidden": "Peau Dure"},
    "Gabite":        {"normal": ["Voile Sable"], "hidden": "Peau Dure"},
    "Garchomp":      {"normal": ["Voile Sable"], "hidden": "Peau Dure"},
    "Munchlax":      {"normal": ["Ramassage", "Isograisse"], "hidden": "Gloutonnerie"},
    "Riolu":         {"normal": ["Impudence", "Attention"], "hidden": "Téméraire"},
    "Lucario":       {"normal": ["Impassible", "Annule Garde"], "hidden": "Justicier"},
    "Hippopotas":    {"normal": ["Sable Volant"], "hidden": "Sable Humide"},
    "Hippowdon":     {"normal": ["Sable Volant"], "hidden": "Sable Humide"},
    "Skorupi":       {"normal": ["Armurbaston", "Sniper"], "hidden": "Regard Vif"},
    "Drapion":       {"normal": ["Armurbaston", "Sniper"], "hidden": "Regard Vif"},
    "Croagunk":      {"normal": ["Anticipation", "Peau Sèche"], "hidden": "Attention"},
    "Toxicroak":     {"normal": ["Anticipation", "Peau Sèche"], "hidden": "Attention"},
    "Carnivine":     {"normal": ["Lévitation"], "hidden": None},
    "Finneon":       {"normal": ["Glissade", "Cuvette"], "hidden": "Pied Véloce"},
    "Lumineon":      {"normal": ["Glissade", "Cuvette"], "hidden": "Pied Véloce"},
    "Mantyke":       {"normal": ["Absorb Eau", "Glissade"], "hidden": "Cuvette"},
    "Snover":        {"normal": ["Alerte Neige"], "hidden": "Anti-Bruit"},
    "Abomasnow":     {"normal": ["Alerte Neige"], "hidden": "Anti-Bruit"},
    "Weavile":       {"normal": ["Pression"], "hidden": "Pickpocket"},
    "Magnezone":     {"normal": ["Magnépiège", "Fermeté"], "hidden": "Analyste"},
    "Lickilicky":    {"normal": ["Benêt", "Gloutonnerie"], "hidden": "Cloud Nine"},
    "Rhyperior":     {"normal": ["Paratonnerre", "Solide Roc"], "hidden": "Téméraire"},
    "Tangrowth":     {"normal": ["Chlorophylle", "Feuille Garde"], "hidden": "Régé-Force"},
    "Electivire":    {"normal": ["Motorisé"], "hidden": "Tension"},
    "Magmortar":     {"normal": ["Corps Ardent"], "hidden": "Esprit Vital"},
    "Togekiss":      {"normal": ["Sérénité", "Joli Sourire"], "hidden": "Chanceux"},
    "Yanmega":       {"normal": ["Turbo", "Lentiteintée"], "hidden": "Frénésie"},
    "Leafeon":       {"normal": ["Feuille Garde"], "hidden": "Chlorophylle"},
    "Glaceon":       {"normal": ["Rideau Neige"], "hidden": "Glissade"},
    "Gliscor":       {"normal": ["Hyper Cutter", "Voile Sable"], "hidden": "Toxitouche"},
    "Mamoswine":     {"normal": ["Isograisse", "Rideau Neige"], "hidden": "Benêt"},
    "Porygon-Z":     {"normal": ["Adaptabilité", "Télécharge"], "hidden": "Analyste"},
    "Gallade":       {"normal": ["Attention"], "hidden": "Téméraire"},
    "Probopass":     {"normal": ["Fermeté", "Magnépiège"], "hidden": "Filtre"},
    "Dusknoir":      {"normal": ["Pression"], "hidden": "Tension"},
    "Froslass":      {"normal": ["Corps Gel"], "hidden": "Attention"},
    "Rotom":         {"normal": ["Lévitation"], "hidden": None},
    "Uxie":          {"normal": ["Lévitation"], "hidden": None},
    "Mesprit":       {"normal": ["Lévitation"], "hidden": None},
    "Azelf":         {"normal": ["Lévitation"], "hidden": None},
    "Dialga":        {"normal": ["Pression"], "hidden": "Télépathe"},
    "Palkia":        {"normal": ["Pression"], "hidden": "Télépathe"},
    "Heatran":       {"normal": ["Torche"], "hidden": "Corps Ardent"},
    "Regigigas":     {"normal": ["Début Calme"], "hidden": None},
    "Giratina":      {"normal": ["Pression"], "hidden": "Télépathe"},
    "Cresselia":     {"normal": ["Lévitation"], "hidden": None},
    "Phione":        {"normal": ["Hydratation"], "hidden": None},
    "Manaphy":       {"normal": ["Hydratation"], "hidden": None},
    "Darkrai":       {"normal": ["Mauvais Rêve"], "hidden": None},
    "Shaymin":       {"normal": ["Médic Nature"], "hidden": None},
    "Silvally-Normal":   {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Fire":     {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Water":    {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Electric": {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Grass":    {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Ice":      {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Fighting": {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Poison":   {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Ground":   {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Flying":   {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Psychic":  {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Bug":      {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Rock":     {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Ghost":    {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Dragon":   {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Dark":     {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Steel":    {"normal": ["Système Alpha"], "hidden": None},
    "Silvally-Fairy":    {"normal": ["Système Alpha"], "hidden": None},
    "Arceus-Normal":   {"normal": ["Multitype"], "hidden": None},
    "Arceus-Fire":     {"normal": ["Multitype"], "hidden": None},
    "Arceus-Water":    {"normal": ["Multitype"], "hidden": None},
    "Arceus-Electric": {"normal": ["Multitype"], "hidden": None},
    "Arceus-Grass":    {"normal": ["Multitype"], "hidden": None},
    "Arceus-Ice":      {"normal": ["Multitype"], "hidden": None},
    "Arceus-Fighting": {"normal": ["Multitype"], "hidden": None},
    "Arceus-Poison":   {"normal": ["Multitype"], "hidden": None},
    "Arceus-Ground":   {"normal": ["Multitype"], "hidden": None},
    "Arceus-Flying":   {"normal": ["Multitype"], "hidden": None},
    "Arceus-Psychic":  {"normal": ["Multitype"], "hidden": None},
    "Arceus-Bug":      {"normal": ["Multitype"], "hidden": None},
    "Arceus-Rock":     {"normal": ["Multitype"], "hidden": None},
    "Arceus-Ghost":    {"normal": ["Multitype"], "hidden": None},
    "Arceus-Dragon":   {"normal": ["Multitype"], "hidden": None},
    "Arceus-Dark":     {"normal": ["Multitype"], "hidden": None},
    "Arceus-Steel":    {"normal": ["Multitype"], "hidden": None},
    "Arceus-Fairy":    {"normal": ["Multitype"], "hidden": None},
    "Victini":       {"normal": ["Victorieux"], "hidden": None},
    "Snivy":         {"normal": ["Engrais"], "hidden": "Acharné"},
    "Servine":       {"normal": ["Engrais"], "hidden": "Acharné"},
    "Serperior":     {"normal": ["Engrais"], "hidden": "Acharné"},
    "Tepig":         {"normal": ["Brasier"], "hidden": "Téméraire"},
    "Pignite":       {"normal": ["Brasier"], "hidden": "Téméraire"},
    "Emboar":        {"normal": ["Brasier"], "hidden": "Téméraire"},
    "Oshawott":      {"normal": ["Torrent"], "hidden": "Coque Armure"},
    "Dewott":        {"normal": ["Torrent"], "hidden": "Coque Armure"},
    "Samurott":      {"normal": ["Torrent"], "hidden": "Coque Armure"},
    "Patrat":        {"normal": ["Regard Vif", "Analyste"], "hidden": "Insomnia"},
    "Watchog":       {"normal": ["Regard Vif", "Analyste"], "hidden": "Insomnia"},
    "Lillipup":      {"normal": ["Ramassage", "Fuite"], "hidden": "Querelleur"},
    "Herdier":       {"normal": ["Intimidation", "Fuite"], "hidden": "Querelleur"},
    "Stoutland":     {"normal": ["Intimidation", "Rideau Neige"], "hidden": "Querelleur"},
    "Purrloin":      {"normal": ["Farceur"], "hidden": "Délestage"},
    "Liepard":       {"normal": ["Farceur"], "hidden": "Délestage"},
    "Pansage":       {"normal": ["Engrais"], "hidden": "Gloutonnerie"},
    "Simisage":      {"normal": ["Engrais"], "hidden": "Gloutonnerie"},
    "Pansear":       {"normal": ["Brasier"], "hidden": "Gloutonnerie"},
    "Simisear":      {"normal": ["Brasier"], "hidden": "Gloutonnerie"},
    "Panpour":       {"normal": ["Torrent"], "hidden": "Gloutonnerie"},
    "Simipour":      {"normal": ["Torrent"], "hidden": "Gloutonnerie"},
    "Munna":         {"normal": ["Prédiction", "Garde Magik"], "hidden": "Télépathe"},
    "Musharna":      {"normal": ["Prédiction", "Garde Magik"], "hidden": "Télépathe"},
    "Pidove":        {"normal": ["Regard Vif", "Coeur de Coq"], "hidden": "Chanceux"},
    "Tranquill":     {"normal": ["Regard Vif", "Coeur de Coq"], "hidden": "Chanceux"},
    "Unfezant":      {"normal": ["Regard Vif", "Coeur de Coq"], "hidden": "Chanceux"},
    "Blitzle":       {"normal": ["Paratonnerre", "Motorisé"], "hidden": "Tension"},
    "Zebstrika":     {"normal": ["Paratonnerre", "Motorisé"], "hidden": "Tension"},
    "Roggenrola":    {"normal": ["Fermeté"], "hidden": "Sable Humide"},
    "Boldore":       {"normal": ["Fermeté"], "hidden": "Sable Humide"},
    "Gigalith":      {"normal": ["Fermeté"], "hidden": "Sable Humide"},
    "Woobat":        {"normal": ["Infiltration", "Coeur Soin"], "hidden": "Simple"},
    "Swoobat":       {"normal": ["Infiltration", "Coeur Soin"], "hidden": "Simple"},
    "Drilbur":       {"normal": ["Voile Sable"], "hidden": "Force Sable"},
    "Excadrill":     {"normal": ["Voile Sable"], "hidden": "Force Sable"},
    "Audino":        {"normal": ["Regard Vif", "Cœur Soin"], "hidden": "Régé-Force"},
    "Timburr":       {"normal": ["Cran", "Annule Garde"], "hidden": "Poing de Fer"},
    "Gurdurr":       {"normal": ["Cran", "Annule Garde"], "hidden": "Poing de Fer"},
    "Conkeldurr":    {"normal": ["Cran", "Annule Garde"], "hidden": "Poing de Fer"},
    "Tympole":       {"normal": ["Glissade", "Hydratation"], "hidden": "Absorb Eau"},
    "Palpitoad":     {"normal": ["Glissade", "Hydratation"], "hidden": "Absorb Eau"},
    "Seismitoad":    {"normal": ["Glissade", "Hydratation"], "hidden": "Absorb Eau"},
    "Throh":         {"normal": ["Cran", "Attention"], "hidden": "Fermeté"},
    "Sawk":          {"normal": ["Cran", "Attention"], "hidden": "Robustesse"},
    "Sewaddle":      {"normal": ["Essaim", "Chlorophylle"], "hidden": "Feuille Garde"},
    "Swadloon":      {"normal": ["Feuille Garde", "Chlorophylle"], "hidden": "Ténacité"},
    "Leavanny":      {"normal": ["Essaim", "Chlorophylle"], "hidden": "Feuille Garde"},
    "Venipede":      {"normal": ["Point Poison", "Essaim"], "hidden": "Vitesse"},
    "Whirlipede":    {"normal": ["Point Poison", "Essaim"], "hidden": "Fuite"},
    "Scolipede":     {"normal": ["Point Poison", "Essaim"], "hidden": "Turbo"},
    "Cottonee":      {"normal": ["Farceur", "Infiltration"], "hidden": "Chlorophylle"},
    "Whimsicott":    {"normal": ["Farceur", "Infiltration"], "hidden": "Chlorophylle"},
    "Petilil":       {"normal": ["Chlorophylle", "Feuille Garde"], "hidden": "Matinal"},
    "Lilligant":     {"normal": ["Chlorophylle", "Feuille Garde"], "hidden": "Matinal"},
    "Basculin-Red-Striped":   {"normal": ["Reckless", "Adaptability"], "hidden": "Brise Moule"},
    "Basculin-Blue-Striped":  {"normal": ["Rock Head", "Adaptability"], "hidden": "Brise Moule"},
    "Basculin-White-Striped": {"normal": ["Phobique"], "hidden": None},
    "Sandile":       {"normal": ["Intimidation", "Annule Garde"], "hidden": "Colérique"},
    "Krokorok":      {"normal": ["Intimidation", "Annule Garde"], "hidden": "Colérique"},
    "Krookodile":    {"normal": ["Intimidation", "Annule Garde"], "hidden": "Colérique"},
    "Darumaka":      {"normal": ["Esprit Vital"], "hidden": "Absentéisme"},
    "Darmanitan":    {"normal": ["Force Pure"], "hidden": "Mode Transe"},
    "Darmanitan-Galarian-Standard": {"normal": ["Gorilla Tactics"], "hidden": "Zen Mode"},
    "Darmanitan-Galarian-Zen":      {"normal": ["Zen Mode"],        "hidden": None},
    "Darmanitan-Zen":               {"normal": ["Zen Mode"],        "hidden": None},
    "Maractus":      {"normal": ["Chlorophylle", "Absorb Eau"], "hidden": "Pickpocket"},
    "Dwebble":       {"normal": ["Fermeté", "Coque Armure"], "hidden": "Acharné"},
    "Crustle":       {"normal": ["Fermeté", "Coque Armure"], "hidden": "Acharné"},
    "Scraggy":       {"normal": ["Mue", "Impudence"], "hidden": "Intimidation"},
    "Scrafty":       {"normal": ["Mue", "Impudence"], "hidden": "Intimidation"},
    "Sigilyph":      {"normal": ["Miracle Skin", "Garde Magik"], "hidden": "Ténacité"},
    "Yamask":        {"normal": ["Momie"], "hidden": None},
    "Cofagrigus":    {"normal": ["Momie"], "hidden": None},
    "Tirtouga":      {"normal": ["Solide Roc", "Fermeté"], "hidden": "Glissade"},
    "Carracosta":    {"normal": ["Solide Roc", "Fermeté"], "hidden": "Glissade"},
    "Archen":        {"normal": ["Défaitiste"], "hidden": None},
    "Archeops":      {"normal": ["Défaitiste"], "hidden": None},
    "Trubbish":      {"normal": ["Puanteur", "Glue"], "hidden": "Boom Final"},
    "Garbodor":      {"normal": ["Puanteur", "Glue"], "hidden": "Boom Final"},
    "Zorua":         {"normal": ["Illusion"], "hidden": None},
    "Zoroark":       {"normal": ["Illusion"], "hidden": None},
    "Minccino":      {"normal": ["Joli Sourire", "Technicien"], "hidden": "Garde Amie"},
    "Cinccino":      {"normal": ["Joli Sourire", "Technicien"], "hidden": "Garde Amie"},
    "Gothita":       {"normal": ["Regard Vif", "Attention"], "hidden": "Oeil Composé"},
    "Gothorita":     {"normal": ["Regard Vif", "Attention"], "hidden": "Oeil Composé"},
    "Gothitelle":    {"normal": ["Regard Vif", "Attention"], "hidden": "Oeil Composé"},
    "Solosis":       {"normal": ["Regard Vif", "Anti-Bruit"], "hidden": "Régé-Force"},
    "Duosion":       {"normal": ["Regard Vif", "Anti-Bruit"], "hidden": "Régé-Force"},
    "Reuniclus":     {"normal": ["Regard Vif", "Anti-Bruit"], "hidden": "Régé-Force"},
    "Ducklett":      {"normal": ["Regard Vif", "Cuvette"], "hidden": "Hydratation"},
    "Swanna":        {"normal": ["Regard Vif", "Cuvette"], "hidden": "Hydratation"},
    "Vanillite":     {"normal": ["Corps Gel", "Rideau Neige"], "hidden": "Armurouillée"},
    "Vanillish":     {"normal": ["Corps Gel", "Rideau Neige"], "hidden": "Armurouillée"},
    "Vanilluxe":     {"normal": ["Corps Gel", "Rideau Neige"], "hidden": "Armurouillée"},
    "Deerling-Spring": {"normal": ["Chlorophyll", "Herbivore"], "hidden": "Sérénité"},
    "Deerling-Summer": {"normal": ["Chlorophyll", "Herbivore"], "hidden": "Sérénité"},
    "Deerling-Autumn": {"normal": ["Chlorophyll", "Herbivore"], "hidden": "Sérénité"},
    "Deerling-Winter": {"normal": ["Chlorophyll", "Herbivore"], "hidden": "Sérénité"},
    "Sawsbuck-Spring": {"normal": ["Chlorophyll", "Herbivore"], "hidden": "Sérénité"},
    "Sawsbuck-Summer": {"normal": ["Chlorophyll", "Herbivore"], "hidden": "Sérénité"},
    "Sawsbuck-Autumn": {"normal": ["Chlorophyll", "Herbivore"], "hidden": "Sérénité"},
    "Sawsbuck-Winter": {"normal": ["Chlorophyll", "Herbivore"], "hidden": "Sérénité"},
    "Emolga":        {"normal": ["Statik", "Motorisé"], "hidden": None},
    "Karrablast":    {"normal": ["Essaim", "Acharné"], "hidden": "Attention"},
    "Escavalier":    {"normal": ["Essaim", "Acharné"], "hidden": "Coque Armure"},
    "Foongus":       {"normal": ["Pose Spore", "Régé-Force"], "hidden": "Anti-Bruit"},
    "Amoonguss":     {"normal": ["Pose Spore", "Régé-Force"], "hidden": "Anti-Bruit"},
    "Frillish":      {"normal": ["Absorb Eau", "Corps Maudit"], "hidden": "Moiteur"},
    "Jellicent":     {"normal": ["Absorb Eau", "Corps Maudit"], "hidden": "Moiteur"},
    "Alomomola":     {"normal": ["Cœur Soin", "Hydratation"], "hidden": "Régé-Force"},
    "Joltik":        {"normal": ["Essaim", "Tension"], "hidden": "Essaim"},
    "Galvantula":    {"normal": ["Essaim", "Tension"], "hidden": "Essaim"},
    "Ferroseed":     {"normal": ["Épine de Fer"], "hidden": "Anti-Bruit"},
    "Ferrothorn":    {"normal": ["Épine de Fer"], "hidden": "Anti-Bruit"},
    "Klink":         {"normal": ["Plus", "Moins"], "hidden": "Corps Sain"},
    "Klang":         {"normal": ["Plus", "Moins"], "hidden": "Corps Sain"},
    "Klinklang":     {"normal": ["Plus", "Moins"], "hidden": "Corps Sain"},
    "Tynamo":        {"normal": ["Lévitation"], "hidden": None},
    "Eelektrik":     {"normal": ["Lévitation"], "hidden": None},
    "Eelektross":    {"normal": ["Lévitation"], "hidden": None},
    "Elgyem":        {"normal": ["Télépathe", "Synchro"], "hidden": "Analyste"},
    "Beheeyem":      {"normal": ["Télépathe", "Synchro"], "hidden": "Analyste"},
    "Litwick":       {"normal": ["Torche", "Corps Ardent"], "hidden": "Infiltration"},
    "Lampent":       {"normal": ["Torche", "Corps Ardent"], "hidden": "Infiltration"},
    "Chandelure":    {"normal": ["Torche", "Corps Ardent"], "hidden": "Infiltration"},
    "Axew":          {"normal": ["Rivalité", "Attention"], "hidden": "Tension"},
    "Fraxure":       {"normal": ["Rivalité", "Attention"], "hidden": "Tension"},
    "Haxorus":       {"normal": ["Rivalité", "Brise Moule"], "hidden": "Tension"},
    "Cubchoo":       {"normal": ["Rideau Neige", "Tension"], "hidden": "Abattant"},
    "Beartic":       {"normal": ["Rideau Neige", "Tension"], "hidden": "Abattant"},
    "Cryogonal":     {"normal": ["Lévitation"], "hidden": None},
    "Shelmet":       {"normal": ["Hydratation", "Coque Armure"], "hidden": "Anti-Bruit"},
    "Accelgor":      {"normal": ["Hydratation", "Gluco-Voile"], "hidden": "Anti-Bruit"},
    "Stunfisk":      {"normal": ["Statik", "Voile Sable"], "hidden": "Absorb Volt"},
    "Mienfoo":       {"normal": ["Regard Vif", "Technicien"], "hidden": "Téméraire"},
    "Mienshao":      {"normal": ["Regard Vif", "Technicien"], "hidden": "Régé-Force"},
    "Druddigon":     {"normal": ["Peau Dure", "Sans Limite"], "hidden": "Brise Moule"},
    "Golett":        {"normal": ["Poing de Fer", "Annule Garde"], "hidden": "Tension"},
    "Golurk":        {"normal": ["Poing de Fer", "Annule Garde"], "hidden": "Tension"},
    "Pawniard":      {"normal": ["Acharné", "Attention"], "hidden": "Pression"},
    "Bisharp":       {"normal": ["Acharné", "Attention"], "hidden": "Pression"},
    "Bouffalant":    {"normal": ["Anti-Bruit", "Téméraire"], "hidden": "Colérique"},
    "Rufflet":       {"normal": ["Regard Vif", "Acharné"], "hidden": "Téméraire"},
    "Braviary":      {"normal": ["Regard Vif", "Acharné"], "hidden": "Téméraire"},
    "Vullaby":       {"normal": ["Coeur de Coq", "Armurouillée"], "hidden": "Tension"},
    "Mandibuzz":     {"normal": ["Coeur de Coq", "Armurouillée"], "hidden": "Tension"},
    "Heatmor":       {"normal": ["Gloutonnerie", "Torche"], "hidden": "Acharné"},
    "Durant":        {"normal": ["Essaim", "Agitation"], "hidden": "Agitation"},
    "Deino":         {"normal": ["Agitation"], "hidden": "Tension"},
    "Zweilous":      {"normal": ["Agitation"], "hidden": "Tension"},
    "Hydreigon":     {"normal": ["Lévitation"], "hidden": None},
    "Larvesta":      {"normal": ["Corps Ardent"], "hidden": "Essaim"},
    "Volcarona":     {"normal": ["Corps Ardent"], "hidden": "Essaim"},
    "Cobalion":      {"normal": ["Coeur Noble"], "hidden": None},
    "Terrakion":     {"normal": ["Coeur Noble"], "hidden": None},
    "Virizion":      {"normal": ["Coeur Noble"], "hidden": None},
    "Tornadus":      {"normal": ["Farceur"], "hidden": "Acharné"},
    "Thundurus":     {"normal": ["Farceur"], "hidden": "Acharné"},
    "Reshiram":      {"normal": ["TurboBrasier"], "hidden": None},
    "Zekrom":        {"normal": ["Téra-Voltage"], "hidden": None},
    "Landorus":      {"normal": ["Force Sable"], "hidden": "Acharné"},
    "Kyurem":        {"normal": ["Pression"], "hidden": None},
    "Keldeo":        {"normal": ["Cœur Noble"], "hidden": None},
    "Meloetta":      {"normal": ["Sérénité"], "hidden": None},
    "Genesect":      {"normal": ["Télécharge"], "hidden": None},
    "Chespin":       {"normal": ["Engrais"], "hidden": "Pare-Balles"},
    "Quilladin":     {"normal": ["Engrais"], "hidden": "Pare-Balles"},
    "Chesnaught":    {"normal": ["Engrais"], "hidden": "Pare-Balles"},
    "Fennekin":      {"normal": ["Brasier"], "hidden": "Magicien"},
    "Braixen":       {"normal": ["Brasier"], "hidden": "Magicien"},
    "Delphox":       {"normal": ["Brasier"], "hidden": "Magicien"},
    "Froakie":       {"normal": ["Torrent"], "hidden": "Protéen"},
    "Frogadier":     {"normal": ["Torrent"], "hidden": "Protéen"},
    "Greninja":      {"normal": ["Torrent"], "hidden": "Protéen"},
    "Greninja-Ash":      {"normal": ["Torrent"], "hidden": "Protéen"},
    "Bunnelby":      {"normal": ["Ramassage", "Agitation"], "hidden": "Coloforce"},
    "Diggersby":     {"normal": ["Ramassage", "Agitation"], "hidden": "Coloforce"},
    "Fletchling":    {"normal": ["Regard Vif"], "hidden": "Ailes Bourrasque"},
    "Fletchinder":   {"normal": ["Corps Ardent"], "hidden": "Ailes Bourrasque"},
    "Talonflame":    {"normal": ["Corps Ardent"], "hidden": "Ailes Bourrasque"},
    "Scatterbug":    {"normal": ["Écran Poudre"], "hidden": "Garde Amie"},
    "Spewpa":        {"normal": ["Écran Poudre"], "hidden": "Garde Amie"},
    "Litleo":        {"normal": ["Rivalité", "Torche"], "hidden": "Tension"},
    "Pyroar":        {"normal": ["Rivalité", "Torche"], "hidden": "Tension"},
    "Flabebe-Red": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Flabebe-Yellow": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Flabebe-Orange": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Flabebe-Blue": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Flabebe-White": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Floette-Red": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Floette-Yellow": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Floette-Orange": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Floette-Blue": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Floette-White": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Florges-Red": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Florges-Yellow": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Florges-Orange": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Florges-Blue": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
"Florges-White": {
    "normal": ["Voile Floral"],
    "hidden": "Symbiose"
},
    "Flabebe-Black": {"normal": ["Fleur Voile"], "hidden": "Symbiose"},
    "Skiddo":        {"normal": ["Herbivore", "Paratonnerre"], "hidden": "Herbivore"},
    "Gogoat":        {"normal": ["Herbivore", "Paratonnerre"], "hidden": "Herbivore"},
    "Pancham":       {"normal": ["Poing de Fer", "Querelleur"], "hidden": "Tension"},
    "Pangoro":       {"normal": ["Poing de Fer", "Querelleur"], "hidden": "Tension"},
    "Furfrou":       {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-Heart":      {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-Star":       {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-Diamond":    {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-Debutante":  {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-Matron":     {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-Dandy":      {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-La-Reine":   {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-Kabuki":     {"normal": ["Toison Épaisse"], "hidden": None},
    "Furfrou-Pharaoh":    {"normal": ["Toison Épaisse"], "hidden": None},
    "Espurr":        {"normal": ["Attention", "Infiltration"], "hidden": "Garde Amie"},
    "Honedge":       {"normal": ["Annule Garde"], "hidden": "Tension"},
    "Doublade":      {"normal": ["Annule Garde"], "hidden": "Tension"},
    "Aegislash-Shield": {"normal": ["Déclic Tactique"], "hidden": None},
    "Aegislash-Blade":  {"normal": ["Déclic Tactique"], "hidden": None},
    "Spritzee":      {"normal": ["Cœur Soin"], "hidden": "Aroma-Voile"},
    "Aromatisse":    {"normal": ["Cœur Soin"], "hidden": "Aroma-Voile"},
    "Swirlix":       {"normal": ["Glucokinésie"], "hidden": "Cœur Soin"},
    "Slurpuff":      {"normal": ["Glucokinésie"], "hidden": "Cœur Soin"},
    "Inkay":         {"normal": ["Contestation", "Infiltration"], "hidden": "Ténacité"},
    "Malamar":       {"normal": ["Contestation", "Infiltration"], "hidden": "Ténacité"},
    "Binacle":       {"normal": ["Poing de Fer", "Sniper"], "hidden": "Pickpocket"},
    "Barbaracle":    {"normal": ["Poing de Fer", "Sniper"], "hidden": "Pickpocket"},
    "Skrelp":        {"normal": ["Poison Point", "Adaptabilité"], "hidden": "Toxitouche"},
    "Dragalge":      {"normal": ["Poison Point", "Adaptabilité"], "hidden": "Toxitouche"},
    "Clauncher":     {"normal": ["Méga Blaster"], "hidden": None},
    "Clawitzer":     {"normal": ["Méga Blaster"], "hidden": None},
    "Helioptile":    {"normal": ["Peau Sèche", "Voile Sable"], "hidden": "Force Soleil"},
    "Heliolisk":     {"normal": ["Peau Sèche", "Voile Sable"], "hidden": "Force Soleil"},
    "Tyrunt":        {"normal": ["Tête de Roc", "Coloforce"], "hidden": "Tension"},
    "Tyrantrum":     {"normal": ["Tête de Roc", "Coloforce"], "hidden": "Tension"},
    "Amaura":        {"normal": ["Corps Gel", "Rideau Neige"], "hidden": "Tension"},
    "Aurorus":       {"normal": ["Corps Gel", "Rideau Neige"], "hidden": "Tension"},
    "Sylveon":       {"normal": ["Joli Sourire"], "hidden": "Pixilate"},
    "Hawlucha":      {"normal": ["Attention", "Sans Limite"], "hidden": "Délestage"},
    "Dedenne":       {"normal": ["Ramassage", "Bajoues"], "hidden": "Minus"},
    "Carbink":       {"normal": ["Fermeté", "Corps Sain"], "hidden": "Fermeté"},
    "Goomy":         {"normal": ["Herbivore", "Hydratation"], "hidden": "Poisseux"},
    "Sliggoo":       {"normal": ["Herbivore", "Hydratation"], "hidden": "Poisseux"},
    "Goodra":        {"normal": ["Herbivore", "Hydratation"], "hidden": "Poisseux"},
    "Klefki":        {"normal": ["Farceur"], "hidden": "Magicien"},
    "Phantump":      {"normal": ["Engrais", "Ramassage"], "hidden": "Moiteur"},
    "Trevenant":     {"normal": ["Engrais", "Ramassage"], "hidden": "Moiteur"},
    "Pumpkaboo":     {"normal": ["Ramassage", "Fuite"], "hidden": "Insomnia"},
    "Gourgeist":     {"normal": ["Ramassage", "Fuite"], "hidden": "Insomnia"},
    "Bergmite":      {"normal": ["Glissade", "Corps Gel"], "hidden": "Fermeté"},
    "Avalugg":       {"normal": ["Glissade", "Corps Gel"], "hidden": "Fermeté"},
    "Noibat":        {"normal": ["Infiltration", "Fuite"], "hidden": "Tension"},
    "Noivern":       {"normal": ["Infiltration", "Fuite"], "hidden": "Tension"},
    "Xerneas":       {"normal": ["Aura Féérique"], "hidden": None},
    "Yveltal":       {"normal": ["Aura Ténébreuse"], "hidden": None},
    "Zygarde":       {"normal": ["Aura Sol"], "hidden": "Essaim Cellulaire"},
    "Diancie":       {"normal": ["Corps Sain"], "hidden": "Fermeté"},
    "Hoopa":         {"normal": ["Magicien"], "hidden": None},
    "Volcanion":     {"normal": ["Absorb Eau"], "hidden": None},
     "Rowlet":        {"normal": ["Engrais"], "hidden": "Longue Portée"},
    "Dartrix":       {"normal": ["Engrais"], "hidden": "Longue Portée"},
    "Decidueye":     {"normal": ["Engrais"], "hidden": "Longue Portée"},
    "Litten":        {"normal": ["Brasier"], "hidden": "Intimidation"},
    "Torracat":      {"normal": ["Brasier"], "hidden": "Intimidation"},
    "Incineroar":    {"normal": ["Brasier"], "hidden": "Intimidation"},
    "Popplio":       {"normal": ["Torrent"], "hidden": "Hydratation"},
    "Brionne":       {"normal": ["Torrent"], "hidden": "Hydratation"},
    "Primarina":     {"normal": ["Torrent"], "hidden": "Hydratation"},
    "Pikipek":       {"normal": ["Regard Vif", "Multi-Coups"], "hidden": "Ramassage"},
    "Trumbeak":      {"normal": ["Regard Vif", "Multi-Coups"], "hidden": "Ramassage"},
    "Toucannon":     {"normal": ["Regard Vif", "Multi-Coups"], "hidden": "Ramassage"},
    "Yungoos":       {"normal": ["Mâchouille", "Adaptabilité"], "hidden": "Agitation"},
    "Gumshoos":      {"normal": ["Mâchouille", "Adaptabilité"], "hidden": "Agitation"},
    "Grubbin":       {"normal": ["Essaim"], "hidden": None},
    "Charjabug":     {"normal": ["Batterie"], "hidden": None},
    "Vikavolt":      {"normal": ["Lévitation"], "hidden": None},
    "Crabrawler":    {"normal": ["Hyper Cutter", "Poing de Fer"], "hidden": "Colérique"},
    "Crabominable":  {"normal": ["Hyper Cutter", "Poing de Fer"], "hidden": "Colérique"},
    "Oricorio-Baile":   {"normal": ["Dancer"], "hidden": None},
    "Oricorio-Pom-Pom": {"normal": ["Dancer"], "hidden": None},
    "Oricorio-Pa'u":    {"normal": ["Dancer"], "hidden": None},
    "Oricorio-Sensu":   {"normal": ["Dancer"], "hidden": None},
    "Cutiefly":      {"normal": ["Écran Poudre", "Régé-Force"], "hidden": "Tension"},
    "Ribombee":      {"normal": ["Écran Poudre", "Régé-Force"], "hidden": "Tension"},
    "Rockruff":      {"normal": ["Regard Vif", "Esprit Vital"], "hidden": "Voix Intérieure"},
    "Lycanroc-Midday": {"normal": ["Regard Vif", "Sand Rush"], "hidden": "Sturdy"},
    "Lycanroc-Midnight": {"normal": ["Sand Rush", "Vital Spirit"], "hidden": "No Guard"},
    "Lycanroc-Dusk": { "normal": ["Tough Claws"], "hidden": None},
    "Wishiwashi-Solo":    {"normal": ["Banc"], "hidden": None},
    "Wishiwashi-School":    {"normal": ["Banc"], "hidden": None},
    "Mareanie":      {"normal": ["Cruauté", "Régé-Force"], "hidden": "Toxitouche"},
    "Toxapex":       {"normal": ["Cruauté", "Régé-Force"], "hidden": "Toxitouche"},
    "Mudbray":       {"normal": ["Tempo Perso", "Téméraire"], "hidden": "Attention"},
    "Mudsdale":      {"normal": ["Tempo Perso", "Téméraire"], "hidden": "Attention"},
    "Dewpider":      {"normal": ["Aquabulle", "Glissade"], "hidden": "Insomnia"},
    "Araquanid":     {"normal": ["Aquabulle", "Glissade"], "hidden": "Insomnia"},
    "Fomantis":      {"normal": ["Feuille Garde"], "hidden": "Contrôle Herbe"},
    "Lurantis":      {"normal": ["Feuille Garde"], "hidden": "Contrôle Herbe"},
    "Morelull":      {"normal": ["Illumination", "Pose Spore"], "hidden": "Effluves"},
    "Shiinotic":     {"normal": ["Illumination", "Pose Spore"], "hidden": "Effluves"},
    "Salandit":      {"normal": ["Corrosion"], "hidden": "Infiltration"},
    "Salazzle":      {"normal": ["Corrosion"], "hidden": "Infiltration"},
    "Stufful":       {"normal": ["Béquet", "Délestage"], "hidden": "Maladresse"},
    "Bewear":        {"normal": ["Béquet", "Délestage"], "hidden": "Maladresse"},
    "Bounsweet":     {"normal": ["Feuille Garde", "Benêt"], "hidden": "Glissade"},
    "Steenee":       {"normal": ["Feuille Garde", "Benêt"], "hidden": "Glissade"},
    "Tsareena":      {"normal": ["Prestance Royale"], "hidden": "Phobique"},
    "Comfey":        {"normal": ["Voile Floral", "Triage"], "hidden": "Gluco-Voile"},
    "Oranguru":      {"normal": ["Télépathe", "Attention"], "hidden": "Symbiose"},
    "Passimian":     {"normal": ["Receveur", "Acharné"], "hidden": "Début Calme"},
    "Wimpod":        {"normal": ["Escampette"], "hidden": None},
    "Golisopod":     {"normal": ["Escampette"], "hidden": None},
    "Sandygast":     {"normal": ["Sable Humide", "Voile Sable"], "hidden": "Gloutonnerie"},
    "Palossand":     {"normal": ["Sable Humide", "Voile Sable"], "hidden": "Gloutonnerie"},
    "Pyukumuku":     {"normal": ["Calque"], "hidden": "Boom Final"},
    "Type: Null":    {"normal": ["Armurouillée"], "hidden": None},
    "Silvally":      {"normal": ["Système Alpha"], "hidden": None},
    "Minior":        {"normal": ["Bouclier Carapace"], "hidden": None},
    "Minior-Red":        {"normal": ["Bouclier-Carcan"], "hidden": None},
    "Minior-Orange":     {"normal": ["Bouclier-Carcan"], "hidden": None},
    "Minior-Yellow":     {"normal": ["Bouclier-Carcan"], "hidden": None},
    "Minior-Green":      {"normal": ["Bouclier-Carcan"], "hidden": None},
    "Minior-Blue":       {"normal": ["Bouclier-Carcan"], "hidden": None},
    "Minior-Indigo":     {"normal": ["Bouclier-Carcan"], "hidden": None},
    "Minior-Violet":     {"normal": ["Bouclier-Carcan"], "hidden": None},
    "Minior-All-Colors": {"normal": ["Bouclier-Carcan"], "hidden": None},
    "Komala":        {"normal": ["Hypersommeil"], "hidden": None},
    "Turtonator":    {"normal": ["Carapace Spéciale"], "hidden": None},
    "Togedemaru":    {"normal": ["Épine de Fer", "Paratonnerre"], "hidden": "Pickpocket"},
    "Mimikyu-Fantômasqued": {"normal": ["Fantômasque"], "hidden": None},
    "Mimikyu-Busted":    {"normal": ["Fantômasque"], "hidden": None},
    "Bruxish":       {"normal": ["Peau Dure", "Attention"], "hidden": "Prognathe"},
    "Drampa":        {"normal": ["Furie", "Infiltration"], "hidden": "Adaptabilité"},
    "Dhelmise":      {"normal": ["Phytomixeur"], "hidden": None},
    "Jangmo-o":      {"normal": ["Anti-Bruit"], "hidden": "Pare-Balles"},
    "Hakamo-o":      {"normal": ["Anti-Bruit"], "hidden": "Pare-Balles"},
    "Kommo-o":       {"normal": ["Anti-Bruit"], "hidden": "Pare-Balles"},
    "Tapu Koko":     {"normal": ["Créa-Élec"], "hidden": "Télépathe"},
    "Tapu Lele":     {"normal": ["Créa-Psy"], "hidden": "Télépathe"},
    "Tapu Bulu":     {"normal": ["Créa-Herbe"], "hidden": "Télépathe"},
    "Tapu Fini":     {"normal": ["Créa-Brume"], "hidden": "Télépathe"},
    "Cosmog":        {"normal": ["Inconscient"], "hidden": None},
    "Cosmoem":       {"normal": ["Inconscient"], "hidden": None},
    "Solgaleo":      {"normal": ["Métallo-Garde"], "hidden": None},
    "Lunala":        {"normal": ["Spectro-Bouclier"], "hidden": None},
    "Nihilego":      {"normal": ["Boost Chimère"], "hidden": None},
    "Buzzwole":      {"normal": ["Boost Chimère"], "hidden": None},
    "Pheromosa":     {"normal": ["Boost Chimère"], "hidden": None},
    "Xurkitree":     {"normal": ["Boost Chimère"], "hidden": None},
    "Celesteela":    {"normal": ["Boost Chimère"], "hidden": None},
    "Kartana":       {"normal": ["Boost Chimère"], "hidden": None},
    "Guzzlord":      {"normal": ["Boost Chimère"], "hidden": None},
    "Necrozma":      {"normal": ["Armure Prismatique"], "hidden": None},
    "Magearna":      {"normal": ["Animacoeur"], "hidden": None},
    "Marshadow":     {"normal": ["Technicien"], "hidden": None},
    "Poipole":       {"normal": ["Boost Chimère"], "hidden": None},
    "Naganadel":     {"normal": ["Boost Chimère"], "hidden": None},
    "Stakataka":     {"normal": ["Boost Chimère"], "hidden": None},
    "Blacephalon":   {"normal": ["Boost Chimère"], "hidden": None},
    "Zeraora":       {"normal": ["Absorb Volt"], "hidden": None},
    "Meltan":        {"normal": ["Magnépiège"], "hidden": None},
    "Melmetal":      {"normal": ["Poing de Fer"], "hidden": None},
    "Grookey":       {"normal": ["Engrais"], "hidden": "Herbivert"},
    "Thwackey":      {"normal": ["Engrais"], "hidden": "Herbivert"},
    "Rillaboom":     {"normal": ["Engrais"], "hidden": "Herbivert"},
    "Scorbunny":     {"normal": ["Brasier"], "hidden": "Libéro"},
    "Raboot":        {"normal": ["Brasier"], "hidden": "Libéro"},
    "Cinderace":     {"normal": ["Brasier"], "hidden": "Libéro"},
    "Sobble":        {"normal": ["Torrent"], "hidden": "Sniper"},
    "Drizzile":      {"normal": ["Torrent"], "hidden": "Sniper"},
    "Inteleon":      {"normal": ["Torrent"], "hidden": "Sniper"},
    "Skwovet":       {"normal": ["Gloutonnerie"], "hidden": "Isograisse"},
    "Greedent":      {"normal": ["Gloutonnerie"], "hidden": "Isograisse"},
    "Rookidee":      {"normal": ["Regard Vif"], "hidden": "Cœur de Fer"},
    "Corvisquire":   {"normal": ["Attention"], "hidden": "Cœur de Fer"},
    "Corviknight":   {"normal": ["Pression", "Miroir Armure"], "hidden": "Cœur de Fer"},
    "Blipbug":       {"normal": ["Essaim"], "hidden": "Télépathe"},
    "Dottler":       {"normal": ["Essaim", "Lentiteintée"], "hidden": "Télépathe"},
    "Orbeetle":      {"normal": ["Essaim", "Lentiteintée"], "hidden": "Télépathe"},
    "Nickit":        {"normal": ["Fuite"], "hidden": "Agitation"},
    "Thievul":       {"normal": ["Fuite"], "hidden": "Agitation"},
    "Gossifleur":    {"normal": ["Regard Vif"], "hidden": "Efflorescence"},
    "Eldegoss":      {"normal": ["Regard Vif"], "hidden": "Efflorescence"},
    "Wooloo":        {"normal": ["Fuite", "Anti-Bruit"], "hidden": "Miroir Magik"},
    "Dubwool":       {"normal": ["Impassible", "Anti-Bruit"], "hidden": "Miroir Magik"},
    "Chewtle":       {"normal": ["Mâchouille", "Coque Armure"], "hidden": "Glissade"},
    "Drednaw":       {"normal": ["Mâchouille", "Coque Armure"], "hidden": "Glissade"},
    "Yamper":        {"normal": ["Ramassage"], "hidden": "Bajoues"},
    "Boltund":       {"normal": ["Voix Intérieure"], "hidden": "Bajoues"},
    "Rolycoly":      {"normal": ["Turbo", "Armurouillée"], "hidden": "Ignifuge"},
    "Carkol":        {"normal": ["Turbo", "Armurouillée"], "hidden": "Ignifuge"},
    "Coalossal":     {"normal": ["Turbo", "Armurouillée"], "hidden": "Ignifuge"},
    "Applin":        {"normal": ["Gloutonnerie", "Rebond"], "hidden": "Cœur de Sève"},
    "Flapple":       {"normal": ["Gloutonnerie", "Rebond"], "hidden": "Cœur de Sève"},
    "Appletun":      {"normal": ["Gloutonnerie", "Rebond"], "hidden": "Cœur de Sève"},
    "Silicobra":     {"normal": ["Voile Sable", "Mue"], "hidden": "Glissade"},
    "Sandaconda":    {"normal": ["Voile Sable", "Mue"], "hidden": "Glissade"},
    "Cramorant":     {"normal": ["Dégobage"], "hidden": None},
    "Arrokuda":      {"normal": ["Propulseur"], "hidden": "Tension"},
    "Barraskewda":   {"normal": ["Propulseur"], "hidden": "Tension"},
    "Toxel":         {"normal": ["Statik", "Punk Rock"], "hidden": "Bajoues"},
    "Toxtricity-Amped":    {"normal": ["Punk Rock", "Technicien"], "hidden": "Boom Final"},
    "Toxtricity-Low-Key":    {"normal": ["Punk Rock", "Technicien"], "hidden": "Boom Final"},
    "Sizzlipede":    {"normal": ["Torche", "Échauffement"], "hidden": "Flamme Libérée"},
    "Centiskorch":   {"normal": ["Torche", "Échauffement"], "hidden": "Flamme Libérée"},
    "Clobbopus":     {"normal": ["Technicien"], "hidden": "Colérique"},
    "Grapploct":     {"normal": ["Technicien"], "hidden": "Colérique"},
    "Sinistea":      {"normal": ["Armurouillée"], "hidden": "Infiltration"},
    "Polteageist":   {"normal": ["Armurouillée"], "hidden": "Infiltration"},
    "Hatenna":       {"normal": ["Anticipation"], "hidden": "Calque"},
    "Hattrem":       {"normal": ["Anticipation"], "hidden": "Calque"},
    "Hatterene":     {"normal": ["Calme"], "hidden": "Magicien"},
    "Impidimp":      {"normal": ["Farceur"], "hidden": "Pickpocket"},
    "Morgrem":       {"normal": ["Farceur"], "hidden": "Pickpocket"},
    "Grimmsnarl":    {"normal": ["Farceur"], "hidden": "Pickpocket"},
    "Obstagoon":     {"normal": ["Acharné", "Attention"], "hidden": "Cœur de Fer"},
    "Perrserker":    {"normal": ["Griffes Acier", "Acharné"], "hidden": "Tension"},
    "Cursola":       {"normal": ["Corps Maudit"], "hidden": "Perceur"},
    "Sirfetch’d":    {"normal": ["Regard Vif", "Acharné"], "hidden": "Querelleur"},
    "Mr. Rime":      {"normal": ["Rideau Neige", "Anti-Bruit"], "hidden": "Glissade"},
    "Runerigus":     {"normal": ["Mummy"], "hidden": None},
    "Milcery":       {"normal": ["Glissade", "Armurouillée"], "hidden": "Aroma-Voile"},
    "Alcremie":      {"normal": ["Glissade", "Armurouillée"], "hidden": "Aroma-Voile"},
    "Falinks":       {"normal": ["Acharné", "Annule Garde"], "hidden": "Attention"},
    "Pincurchin":    {"normal": ["Épine de Fer"], "hidden": "Créa-Élec"},
    "Snom":          {"normal": ["Rideau Neige"], "hidden": "Peau Gelée"},
    "Frosmoth":      {"normal": ["Écran Poudre"], "hidden": "Peau Gelée"},
    "Stonjourner":   {"normal": ["Corps Sain"], "hidden": "Force Pie"},
    "Indeedee-Male": {
    "normal": ["Attention", "Synchro"],
    "hidden": "Créa-Psy"
},
"Indeedee-Female": {
    "normal": ["Tempo Perso", "Synchro"],
    "hidden": "Créa-Psy"
},
    "Morpeko":       {"normal": ["Voracité"], "hidden": None},
    "Morpeko-Hangry":       {"normal": ["Voracité"], "hidden": None},
    "Cufant":        {"normal": ["Force Hercule"], "hidden": "Anti-Bruit"},
    "Copperajah":    {"normal": ["Force Hercule"], "hidden": "Anti-Bruit"},
    "Dracozolt":     {"normal": ["Absorb Volt", "Statik"], "hidden": "Sable Humide"},
    "Arctozolt":     {"normal": ["Absorb Volt", "Statik"], "hidden": "Sable Humide"},
    "Dracovish":     {"normal": ["Poisson Bouclier", "Fermeté"], "hidden": "Sable Humide"},
    "Arctovish":     {"normal": ["Poisson Bouclier", "Fermeté"], "hidden": "Sable Humide"},
    "Duraludon":     {"normal": ["Tension", "Fermeté"], "hidden": "Allié Nuage"},
    "Dreepy":        {"normal": ["Lévitation", "Infiltration"], "hidden": "Corps Maudit"},
    "Drakloak":      {"normal": ["Lévitation", "Infiltration"], "hidden": "Corps Maudit"},
    "Dragapult":     {"normal": ["Lévitation", "Infiltration"], "hidden": "Corps Maudit"},
    "Zacian":        {"normal": ["Épée Indomptable"], "hidden": None},
    "Zamazenta":     {"normal": ["Bouclier Indomptable"], "hidden": None},
    "Zacian-Crowned":        {"normal": ["Épée Indomptable"], "hidden": None},
    "Zamazenta-crowned":     {"normal": ["Bouclier Indomptable"], "hidden": None},
    "Eternatus":     {"normal": ["Pression"], "hidden": None},
    "Eternatus-Eternamax": {"normal": ["Pression"], "hidden": None},
    "Kubfu":         {"normal": ["Attention"], "hidden": "Acharné"},
    "Zarude":        {"normal": ["Feuille Garde"], "hidden": None},
    "Zarude-Dada":        {"normal": ["Feuille Garde"], "hidden": None},
    "Regieleki":     {"normal": ["Absorb Volt"], "hidden": None},
    "Regidrago":     {"normal": ["Dent de Dragon"], "hidden": None},
    "Glastrier":     {"normal": ["Acharné"], "hidden": None},
    "Spectrier":     {"normal": ["Acharné"], "hidden": None},
    "Calyrex":       {"normal": ["Tension"], "hidden": None},
    "Calyrex": {"normal": ["Unnerve"], "hidden": None},
    "Calyrex-Ice": {"normal": ["As One (Glastrier)"], "hidden": None},
    "Calyrex-Shadow": {"normal": ["As One (Spectrier)"], "hidden": None},
    "Sprigatito":    {"normal": ["Engrais"], "hidden": "Protéen"},
    "Floragato":     {"normal": ["Engrais"], "hidden": "Protéen"},
    "Meowscarada":   {"normal": ["Engrais"], "hidden": "Protéen"},
    "Fuecoco":       {"normal": ["Brasier"], "hidden": "Inconscient"},
    "Crocalor":      {"normal": ["Brasier"], "hidden": "Inconscient"},
    "Skeledirge":    {"normal": ["Brasier"], "hidden": "Inconscient"},
    "Quaxly":        {"normal": ["Torrent"], "hidden": "Danseuse"},
    "Quaxwell":      {"normal": ["Torrent"], "hidden": "Danseuse"},
    "Quaquaval":     {"normal": ["Torrent"], "hidden": "Danseuse"},
    "Lechonk":       {"normal": ["Aroma-Voile", "Gloutonnerie"], "hidden": "Isograisse"},
    "Oinkologne-Male": {"normal": ["Lingering Aroma", "Gluttony"], "hidden": "Thick Fat"},
    "Oinkologne-Female": {"normal": ["Aroma Veil", "Gluttony"], "hidden": "Thick Fat"},
    "Tarountula":    {"normal": ["Toile Armure"], "hidden": "Essaim"},
    "Spidops":       {"normal": ["Toile Armure"], "hidden": "Essaim"},
    "Nymble":        {"normal": ["Essaim"], "hidden": "Agitation"},
    "Lokix":         {"normal": ["Essaim"], "hidden": "Agitation"},
    "Rellor":        {"normal": ["Pied Véloce"], "hidden": "Garde Amie"},
    "Rabsca":        {"normal": ["Pied Véloce"], "hidden": "Garde Amie"},
    "Greavard":      {"normal": ["Ramassage"], "hidden": "Isolation"},
    "Houndstone":    {"normal": ["Ramassage"], "hidden": "Isolation"},
    "Flittle":       {"normal": ["Anticipation"], "hidden": "Speed Boost"},
    "Espathra":      {"normal": ["Anticipation"], "hidden": "Speed Boost"},
    "Farigiraf":     {"normal": ["Ruminant", "Filtre"], "hidden": "Armurouillée"},
    "Wiglett":       {"normal": ["Glissade", "Voile Sable"], "hidden": "Cuvette"},
    "Wugtrio":       {"normal": ["Glissade", "Voile Sable"], "hidden": "Cuvette"},
    "Dondozo":       {"normal": ["Ignifuge", "Benêt"], "hidden": "Tension"},
   "Tatsugiri-Curly": {
    "normal": ["Commandant", "Collecteur"],
    "hidden": "Tempo Perso"
},
"Tatsugiri-Droopy": {
    "normal": ["Commandant", "Collecteur"],
    "hidden": "Tempo Perso"
},
"Tatsugiri-Stretchy": {
    "normal": ["Commandant", "Collecteur"],
    "hidden": "Tempo Perso"
},
    "Annihilape":    {"normal": ["Attention", "Téméraire"], "hidden": "Colérique"},
    "Clodsire":      {"normal": ["Poison Point", "Absorb Eau"], "hidden": "Inconscient"},
    "Kingambit":     {"normal": ["Acharné", "Attention"], "hidden": "Impérialisme"},
    "Great Tusk":    {"normal": ["Protosynthèse"], "hidden": None},
    "Scream Tail":   {"normal": ["Protosynthèse"], "hidden": None},
    "Brute Bonnet":  {"normal": ["Protosynthèse"], "hidden": None},
    "Flutter Mane":  {"normal": ["Protosynthèse"], "hidden": None},
    "Slither Wing":  {"normal": ["Protosynthèse"], "hidden": None},
    "Sandy Shocks":  {"normal": ["Protosynthèse"], "hidden": None},
    "Iron Treads":   {"normal": ["Charge Quantique"], "hidden": None},
    "Iron Bundle":   {"normal": ["Charge Quantique"], "hidden": None},
    "Iron Hands":    {"normal": ["Charge Quantique"], "hidden": None},
    "Iron Jugulis":  {"normal": ["Charge Quantique"], "hidden": None},
    "Iron Moth":     {"normal": ["Charge Quantique"], "hidden": None},
    "Iron Thorns":   {"normal": ["Charge Quantique"], "hidden": None},
    "Frigibax":      {"normal": ["Thermo-Échange"], "hidden": "Brise Glace"},
    "Arctibax":      {"normal": ["Thermo-Échange"], "hidden": "Brise Glace"},
    "Baxcalibur":    {"normal": ["Thermo-Échange"], "hidden": "Brise Glace"},
    "Gholdengo":     {"normal": ["Corps En Or"], "hidden": None},
    "Wo-Chien":      {"normal": ["Tableau Maléfique"], "hidden": None},
    "Chien-Pao":     {"normal": ["Lames Maléfiques"], "hidden": None},
    "Ting-Lu":       {"normal": ["Vase Maléfique"], "hidden": None},
    "Chi-Yu":        {"normal": ["Flammes Maléfiques"], "hidden": None},
    "Roaring Moon":  {"normal": ["Protosynthèse"], "hidden": None},
    "Iron Valiant":  {"normal": ["Charge Quantique"], "hidden": None},
    "Koraidon":      {"normal": ["Pouls Orichalque"], "hidden": None},
    "Miraidon":      {"normal": ["Moteur Hadron"], "hidden": None},
    "Walking Wake":  {"normal": ["Protosynthèse"], "hidden": None},
    "Iron Leaves":   {"normal": ["Charge Quantique"], "hidden": None},
    "Dipplin":       {"normal": ["Gloutonnerie", "Rebond"], "hidden": "Douceur"},
    "Poltchageist":  {"normal": ["Armurouillée"], "hidden": "Hospitalité"},
    "Sinistcha":     {"normal": ["Armurouillée"], "hidden": "Hospitalité"},
    "Okidogi":       {"normal": ["Toxitouche"], "hidden": None},
    "Munkidori":     {"normal": ["Cruauté"], "hidden": None},
    "Fezandipiti":   {"normal": ["Cœur Soin"], "hidden": None},
    "Archaludon":    {"normal": ["Laser Concentré", "Corps Sain"], "hidden": "Anti-Bruit"},
    "Hydrapple":     {"normal": ["Rebond", "Gloutonnerie"], "hidden": "Douceur"},
    "Gouging Fire":  {"normal": ["Protosynthèse"], "hidden": None},
    "Raging Bolt":   {"normal": ["Protosynthèse"], "hidden": None},
    "Iron Boulder":  {"normal": ["Charge Quantique"], "hidden": None},
    "Iron Crown":    {"normal": ["Charge Quantique"], "hidden": None},
    "Terapagos":     {"normal": ["Téra-Carapace"], "hidden": None},
    "Pecharunt":     {"normal": ["Chaîne Toxique"], "hidden": None},
    "Growlithe-Hisui":  {"normal": ["Intimidation", "Torche"], "hidden": "Cœur Noble"},
    "Arcanine-Hisui":   {"normal": ["Intimidation", "Torche"], "hidden": "Cœur Noble"},
    "Voltorb-Hisui":    {"normal": ["Anti-Bruit", "Statik"], "hidden": "Boom Final"},
    "Electrode-Hisui":  {"normal": ["Anti-Bruit", "Statik"], "hidden": "Boom Final"},
    "Zigzagoon-Galar":  {"normal": ["Ramassage", "Gloutonnerie"], "hidden": "Pied Véloce"},
    "Linoone-Galar":    {"normal": ["Ramassage", "Gloutonnerie"], "hidden": "Pied Véloce"},
    "Darumaka-Galar":   {"normal": ["Agitation"], "hidden": "Attention"},
    "Ponyta-Galar":     {"normal": ["Fuite", "Voile Pastel"], "hidden": "Anticipation"},
    "Rapidash-Galar":   {"normal": ["Fuite", "Voile Pastel"], "hidden": "Anticipation"},
    "Rattata-Alola":    {"normal": ["Gloutonnerie", "Agitation"], "hidden": "Isograisse"},
    "Raticate-Alola":   {"normal": ["Gloutonnerie", "Agitation"], "hidden": "Isograisse"},
    "Raichu-Alola":     {"normal": ["Surf Caudal"], "hidden": None},
    "Sandshrew-Alola":  {"normal": ["Rideau Neige"], "hidden": "Chasse-Neige"},
    "Sandslash-Alola":  {"normal": ["Rideau Neige"], "hidden": "Chasse-Neige"},
    "Vulpix-Alola":     {"normal": ["Rideau Neige"], "hidden": "Alerte Neige"},
    "Ninetales-Alola":  {"normal": ["Rideau Neige"], "hidden": "Alerte Neige"},
    "Diglett-Alola":    {"normal": ["Voile Sable", "Mèche Rebelle"], "hidden": "Force Sable"},
    "Dugtrio-Alola":    {"normal": ["Voile Sable", "Mèche Rebelle"], "hidden": "Force Sable"},
    "Meowth-Alola":     {"normal": ["Ramassage", "Technicien"], "hidden": "Phobique"},
    "Persian-Alola":    {"normal": ["Toison Épaisse", "Technicien"], "hidden": "Phobique"}
}

def generate_pokemon(name: str, rarity: str, chroma_bonus: int = 0):
    forced_shiny = name.startswith("shiny_")
    base_name = name.replace("shiny_", "")

    from core.translation_data import POKEMON_NAMES
    for eng, names in POKEMON_NAMES.items():
        if base_name == names.get("fr") or base_name == names.get("en"):
            base_name = eng
            break
    
    shiny_chance = 1 / 4096 + (chroma_bonus * 0.05)
    shiny = forced_shiny or (random.random() < shiny_chance)

    if shiny:
        ivs = {stat: 31 for stat in ["hp", "atk", "def", "spa", "spd", "spe"]}
    else:
        ivs = {stat: random.randint(0, 31) for stat in ["hp", "atk", "def", "spa", "spd", "spe"]}

    nature = random.choice(list(NATURES))

    # Récupération des talents
    talents = POKEMON_TALENTS.get(base_name, {})
    normal_abilities = talents.get("normal", [])
    hidden_ability = talents.get("hidden")

    # Par défaut on met Aucun si aucune data trouvée
    ability = "Aucun"

    if hidden_ability and random.random() < 0.02:
        ability = hidden_ability
    elif normal_abilities:
        ability = random.choice(normal_abilities)


    return {
        "name": name,
        "rarity": rarity,
        "shiny": shiny,
        "ivs": ivs,
        "nature": nature,
        "ability": ability,
        "hidden_ability": hidden_ability,
        "level": 1,
        "quantity": 1
    }

def get_pokemon_stats_and_moves(pkm):
    # Si le Pokémon a déjà ses stats enregistrées, on les utilise
    stats = pkm.get("stats", {
        "hp": 100,
        "attack": 50,
        "defense": 50,
        "speed": 50,
    })

    # Construction des attaques avec PP depuis ton moves.json
    moves = []
    for move_name in pkm.get("moves", []):
        move_data = get_move(move_name)
        if move_data:
            moves.append({
                "name": move_data["name"],
                "power": move_data["power"],
                "pp": move_data["pp"]
            })

    return stats, moves
